CREATE TABLE amr_report_campy( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_filename" TEXT,
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "resfinder_pointfinder_software_version" TEXT,
  "resfinder_database_download_date" TEXT,
  "id_threshold_percentage_resfinder" TEXT,
  "min_length_threshold_percentage_resfinder" TEXT,
  "pointfinder_database_download_date" TEXT,
  "id_threshold_percentage_pointfinder" TEXT,
  "min_length_threshold_percentage_pointfinder" TEXT,
  "resfinder_brief" TEXT,
  "resfinder_detailed" TEXT,
  "class_pheno_table_antibiotics_pheno_table" TEXT,
  "spectinomycin_aminocyclitol" TEXT,
  "unknown aminocyclitol_aminocyclitol" TEXT,
  "amikacin_aminoglycoside" TEXT,
  "apramycin_aminoglycoside" TEXT,
  "arbekacin_aminoglycoside" TEXT,
  "astromicin_aminoglycoside" TEXT,
  "butiromycin_aminoglycoside" TEXT,
  "butirosin_aminoglycoside" TEXT,
  "capreomycin_aminoglycoside" TEXT,
  "dibekacin_aminoglycoside" TEXT,
  "fortimicin_aminoglycoside" TEXT,
  "g418_aminoglycoside" TEXT,
  "gentamicin_aminoglycoside" TEXT,
  "gentamicin c_aminoglycoside" TEXT,
  "hygromycin_aminoglycoside" TEXT,
  "isepamicin_aminoglycoside" TEXT,
  "kanamycin_aminoglycoside" TEXT,
  "kanamycin a_aminoglycoside" TEXT,
  "kasugamycin_aminoglycoside" TEXT,
  "lividomycin_aminoglycoside" TEXT,
  "neomycin_aminoglycoside" TEXT,
  "netilmicin_aminoglycoside" TEXT,
  "paromomycin_aminoglycoside" TEXT,
  "ribostamycin_aminoglycoside" TEXT,
  "sisomicin_aminoglycoside" TEXT,
  "streptomycin_aminoglycoside" TEXT,
  "tobramycin_aminoglycoside" TEXT,
  "unknown aminoglycoside_aminoglycoside" TEXT,
  "chloramphenicol_phenicol" TEXT,
  "florfenicol_phenicol" TEXT,
  "unknown amphenicol_phenicol" TEXT,
  "unknown phenicol_phenicol" TEXT,
  "d-cycloserine_analog of d-alanine" TEXT,
  "unknown analog of d-alanine_analog of d-alanine" TEXT,
  "amoxicillin_beta-lactam" TEXT,
  "amoxicillin+clavulanic acid_beta-lactam" TEXT,
  "ampicillin_beta-lactam" TEXT,
  "ampicillin+clavulanic acid_beta-lactam" TEXT,
  "aztreonam_beta-lactam" TEXT,
  "cefazolin_beta-lactam" TEXT,
  "cefepime_beta-lactam" TEXT,
  "cefixime_beta-lactam" TEXT,
  "cefotaxime_beta-lactam" TEXT,
  "cefotaxime+clavulanic acid_beta-lactam" TEXT,
  "cefoxitin_beta-lactam" TEXT,
  "ceftaroline_beta-lactam" TEXT,
  "ceftazidime_beta-lactam" TEXT,
  "ceftazidime+avibactam_beta-lactam" TEXT,
  "ceftriaxone_beta-lactam" TEXT,
  "cefuroxime_beta-lactam" TEXT,
  "cephalothin_beta-lactam" TEXT,
  "cephalotin_beta-lactam" TEXT,
  "ertapenem_beta-lactam" TEXT,
  "imipenem_beta-lactam" TEXT,
  "meropenem_beta-lactam" TEXT,
  "penicillin_beta-lactam" TEXT,
  "piperacillin_beta-lactam" TEXT,
  "piperacillin+clavulanic acid_beta-lactam" TEXT,
  "piperacillin+tazobactam_beta-lactam" TEXT,
  "temocillin_beta-lactam" TEXT,
  "ticarcillin_beta-lactam" TEXT,
  "ticarcillin+clavulanic acid_beta-lactam" TEXT,
  "unknown beta-lactam_beta-lactam" TEXT,
  "bedaquiline_diarylquinoline" TEXT,
  "unknown diarylquinoline_diarylquinoline" TEXT,
  "sulfamethoxazole_folate pathway antagonist" TEXT,
  "trimethoprim_folate pathway antagonist" TEXT,
  "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
  "fosfomycin_fosfomycin" TEXT,
  "unknown fosfomycin_fosfomycin" TEXT,
  "teicoplanin_glycopeptide" TEXT,
  "vancomycin_glycopeptide" TEXT,
  "unknown glycopeptide_glycopeptide" TEXT,
  "clofazimine_iminophenazine" TEXT,
  "unknown iminophenazine_iminophenazine" TEXT,
  "isoniazid_isonicotinic acid hydrazide" TEXT,
  "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
  "clindamycin_lincosamide" TEXT,
  "lincomycin_lincosamide" TEXT,
  "unknown lincosamide_lincosamide" TEXT,
  "azithromycin_macrolide" TEXT,
  "carbomycin_macrolide" TEXT,
  "erythromycin_macrolide" TEXT,
  "oleandomycin_macrolide" TEXT,
  "spiramycin_macrolide" TEXT,
  "telithromycin_macrolide" TEXT,
  "tylosin_macrolide" TEXT,
  "unknown macrolide_macrolide" TEXT,
  "metronidazole_nitroimidazole" TEXT,
  "unknown nitroimidazole_nitroimidazole" TEXT,
  "linezolid_oxazolidinone" TEXT,
  "unknown oxazolidinone_oxazolidinone" TEXT,
  "tiamulin_pleuromutilin" TEXT,
  "unknown pleuromutilin_pleuromutilin" TEXT,
  "colistin_polymyxin" TEXT,
  "unknown polymyxin_polymyxin" TEXT,
  "mupirocin_pseudomonic acid" TEXT,
  "unknown pseudomonic acid_pseudomonic acid" TEXT,
  "ciprofloxacin_quinolone" TEXT,
  "fluoroquinolone_quinolone" TEXT,
  "nalidixic acid_quinolone" TEXT,
  "unknown quinolone_quinolone" TEXT,
  "unknown fluoroquinolone_quinolone" TEXT,
  "rifampicin_rifamycin" TEXT,
  "unknown rifamycin_rifamycin" TEXT,
  "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
  "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
  "fusidic acid_steroid antibacterial" TEXT,
  "unknown steroid antibacterial_steroid antibacterial" TEXT,
  "dalfopristin_streptogramin a" TEXT,
  "pristinamycin iia_streptogramin a" TEXT,
  "quinupristin+dalfopristin_streptogramin a" TEXT,
  "unknown streptogramin a_streptogramin a" TEXT,
  "virginiamycin m_streptogramin a" TEXT,
  "pristinamycin ia_streptogramin b" TEXT,
  "quinupristin_streptogramin b" TEXT,
  "virginiamycin s_streptogramin b" TEXT,
  "unknown streptogramin b_streptogramin b" TEXT,
  "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
  "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
  "doxycycline_tetracycline" TEXT,
  "minocycline_tetracycline" TEXT,
  "tetracycline_tetracycline" TEXT,
  "tigecycline_tetracycline" TEXT,
  "unknown tetracycline_tetracycline" TEXT,
  "ethionamide_thioamide" TEXT,
  "unknown thioamide_thioamide" TEXT,
  "carbapenem_under_development" TEXT,
  "ceftiofur_under_development" TEXT,
  "cephalosporins_under_development" TEXT,
  "fluoroquinolone_under_development" TEXT,
  "norfloxacin_under_development" TEXT,
  "ethambutol_unspecified" TEXT,
  "unknown unspecified_unspecified" TEXT,
  "class_pheno_table_disinfectants_pheno_table" TEXT,
  "formaldehyde_aldehydes" TEXT,
  "unknown aldehyde_aldehydes" TEXT,
  "temperature_heat" TEXT,
  "hydrogen peroxide_peroxides" TEXT,
  "unknown peroxide_peroxides" TEXT,
  "benzylkonium chloride_quaternary ammonium compounds" TEXT,
  "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
  "chlorhexidine_quaternary ammonium compounds" TEXT,
  "ethidium bromide_quaternary ammonium compounds" TEXT,
  "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
  "#pointfinder" TEXT,
  "ampC_promoter_size_53bp" TEXT,
  "folP" TEXT,
  "gyrA" TEXT,
  "gyrB" TEXT,
  "parC" TEXT,
  "parE" TEXT,
  "pmrA" TEXT,
  "pmrB" TEXT,
  "rpoB" TEXT,
  "16S_rrsB" TEXT,
  "16S_rrsC" TEXT,
  "16S_rrsH" TEXT,
  "23S" TEXT,
  "rpsL" TEXT,
  "cmeR" TEXT
);

CREATE TABLE amr_report_ecoli( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255), 
  "MLST_filename" TEXT,
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "resfinder_pointfinder_software_version" TEXT,
  "resfinder_database_download_date" TEXT,
  "id_threshold_percentage_resfinder" TEXT,
  "min_length_threshold_percentage_resfinder" TEXT,
  "pointfinder_database_download_date" TEXT,
  "id_threshold_percentage_pointfinder" TEXT,
  "min_length_threshold_percentage_pointfinder" TEXT,
  "resfinder_brief" TEXT,
  "resfinder_detailed" TEXT,
  "class_pheno_table_antibiotics_pheno_table" TEXT,
  "spectinomycin_aminocyclitol" TEXT,
  "unknown aminocyclitol_aminocyclitol" TEXT,
  "amikacin_aminoglycoside" TEXT,
  "apramycin_aminoglycoside" TEXT,
  "arbekacin_aminoglycoside" TEXT,
  "astromicin_aminoglycoside" TEXT,
  "butiromycin_aminoglycoside" TEXT,
  "butirosin_aminoglycoside" TEXT,
  "capreomycin_aminoglycoside" TEXT,
  "dibekacin_aminoglycoside" TEXT,
  "fortimicin_aminoglycoside" TEXT,
  "g418_aminoglycoside" TEXT,
  "gentamicin_aminoglycoside" TEXT,
  "gentamicin c_aminoglycoside" TEXT,
  "hygromycin_aminoglycoside" TEXT,
  "isepamicin_aminoglycoside" TEXT,
  "kanamycin_aminoglycoside" TEXT,
  "kanamycin a_aminoglycoside" TEXT,
  "kasugamycin_aminoglycoside" TEXT,
  "lividomycin_aminoglycoside" TEXT,
  "neomycin_aminoglycoside" TEXT,
  "netilmicin_aminoglycoside" TEXT,
  "paromomycin_aminoglycoside" TEXT,
  "ribostamycin_aminoglycoside" TEXT,
  "sisomicin_aminoglycoside" TEXT,
  "streptomycin_aminoglycoside" TEXT,
  "tobramycin_aminoglycoside" TEXT,
  "unknown aminoglycoside_aminoglycoside" TEXT,
  "chloramphenicol_phenicol" TEXT,
  "florfenicol_phenicol" TEXT,
  "unknown amphenicol_phenicol" TEXT,
  "unknown phenicol_phenicol" TEXT,
  "d-cycloserine_analog of d-alanine" TEXT,
  "unknown analog of d-alanine_analog of d-alanine" TEXT,
  "amoxicillin_beta-lactam" TEXT,
  "amoxicillin+clavulanic acid_beta-lactam" TEXT,
  "ampicillin_beta-lactam" TEXT,
  "ampicillin+clavulanic acid_beta-lactam" TEXT,
  "aztreonam_beta-lactam" TEXT,
  "cefazolin_beta-lactam" TEXT,
  "cefepime_beta-lactam" TEXT,
  "cefixime_beta-lactam" TEXT,
  "cefotaxime_beta-lactam" TEXT,
  "cefotaxime+clavulanic acid_beta-lactam" TEXT,
  "cefoxitin_beta-lactam" TEXT,
  "ceftaroline_beta-lactam" TEXT,
  "ceftazidime_beta-lactam" TEXT,
  "ceftazidime+avibactam_beta-lactam" TEXT,
  "ceftriaxone_beta-lactam" TEXT,
  "cefuroxime_beta-lactam" TEXT,
  "cephalothin_beta-lactam" TEXT,
  "cephalotin_beta-lactam" TEXT,
  "ertapenem_beta-lactam" TEXT,
  "imipenem_beta-lactam" TEXT,
  "meropenem_beta-lactam" TEXT,
  "penicillin_beta-lactam" TEXT,
  "piperacillin_beta-lactam" TEXT,
  "piperacillin+clavulanic acid_beta-lactam" TEXT,
  "piperacillin+tazobactam_beta-lactam" TEXT,
  "temocillin_beta-lactam" TEXT,
  "ticarcillin_beta-lactam" TEXT,
  "ticarcillin+clavulanic acid_beta-lactam" TEXT,
  "unknown beta-lactam_beta-lactam" TEXT,
  "bedaquiline_diarylquinoline" TEXT,
  "unknown diarylquinoline_diarylquinoline" TEXT,
  "sulfamethoxazole_folate pathway antagonist" TEXT,
  "trimethoprim_folate pathway antagonist" TEXT,
  "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
  "fosfomycin_fosfomycin" TEXT,
  "unknown fosfomycin_fosfomycin" TEXT,
  "teicoplanin_glycopeptide" TEXT,
  "vancomycin_glycopeptide" TEXT,
  "unknown glycopeptide_glycopeptide" TEXT,
  "clofazimine_iminophenazine" TEXT,
  "unknown iminophenazine_iminophenazine" TEXT,
  "isoniazid_isonicotinic acid hydrazide" TEXT,
  "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
  "clindamycin_lincosamide" TEXT,
  "lincomycin_lincosamide" TEXT,
  "unknown lincosamide_lincosamide" TEXT,
  "azithromycin_macrolide" TEXT,
  "carbomycin_macrolide" TEXT,
  "erythromycin_macrolide" TEXT,
  "oleandomycin_macrolide" TEXT,
  "spiramycin_macrolide" TEXT,
  "telithromycin_macrolide" TEXT,
  "tylosin_macrolide" TEXT,
  "unknown macrolide_macrolide" TEXT,
  "metronidazole_nitroimidazole" TEXT,
  "unknown nitroimidazole_nitroimidazole" TEXT,
  "linezolid_oxazolidinone" TEXT,
  "unknown oxazolidinone_oxazolidinone" TEXT,
  "tiamulin_pleuromutilin" TEXT,
  "unknown pleuromutilin_pleuromutilin" TEXT,
  "colistin_polymyxin" TEXT,
  "unknown polymyxin_polymyxin" TEXT,
  "mupirocin_pseudomonic acid" TEXT,
  "unknown pseudomonic acid_pseudomonic acid" TEXT,
  "ciprofloxacin_quinolone" TEXT,
  "fluoroquinolone_quinolone" TEXT,
  "nalidixic acid_quinolone" TEXT,
  "unknown quinolone_quinolone" TEXT,
  "unknown fluoroquinolone_quinolone" TEXT,
  "rifampicin_rifamycin" TEXT,
  "unknown rifamycin_rifamycin" TEXT,
  "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
  "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
  "fusidic acid_steroid antibacterial" TEXT,
  "unknown steroid antibacterial_steroid antibacterial" TEXT,
  "dalfopristin_streptogramin a" TEXT,
  "pristinamycin iia_streptogramin a" TEXT,
  "quinupristin+dalfopristin_streptogramin a" TEXT,
  "unknown streptogramin a_streptogramin a" TEXT,
  "virginiamycin m_streptogramin a" TEXT,
  "pristinamycin ia_streptogramin b" TEXT,
  "quinupristin_streptogramin b" TEXT,
  "virginiamycin s_streptogramin b" TEXT,
  "unknown streptogramin b_streptogramin b" TEXT,
  "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
  "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
  "doxycycline_tetracycline" TEXT,
  "minocycline_tetracycline" TEXT,
  "tetracycline_tetracycline" TEXT,
  "tigecycline_tetracycline" TEXT,
  "unknown tetracycline_tetracycline" TEXT,
  "ethionamide_thioamide" TEXT,
  "unknown thioamide_thioamide" TEXT,
  "carbapenem_under_development" TEXT,
  "ceftiofur_under_development" TEXT,
  "cephalosporins_under_development" TEXT,
  "fluoroquinolone_under_development" TEXT,
  "norfloxacin_under_development" TEXT,
  "ethambutol_unspecified" TEXT,
  "unknown unspecified_unspecified" TEXT,
  "class_pheno_table_disinfectants_pheno_table" TEXT,
  "formaldehyde_aldehydes" TEXT,
  "unknown aldehyde_aldehydes" TEXT,
  "temperature_heat" TEXT,
  "hydrogen peroxide_peroxides" TEXT,
  "unknown peroxide_peroxides" TEXT,
  "benzylkonium chloride_quaternary ammonium compounds" TEXT,
  "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
  "chlorhexidine_quaternary ammonium compounds" TEXT,
  "ethidium bromide_quaternary ammonium compounds" TEXT,
  "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
  "#pointfinder" TEXT,
  "ampC_promoter_size_53bp" TEXT,
  "folP" TEXT,
  "gyrA" TEXT,
  "gyrB" TEXT,
  "parC" TEXT,
  "parE" TEXT,
  "pmrA" TEXT,
  "pmrB" TEXT,
  "rpoB" TEXT,
  "16S_rrsB" TEXT,
  "16S_rrsC" TEXT,
  "16S_rrsH" TEXT,
  "23S" TEXT
);

CREATE TABLE amr_report_listeria( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_filename" TEXT,
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "resfinder_pointfinder_software_version" TEXT,
  "resfinder_database_download_date" TEXT,
  "id_threshold_percentage_resfinder" TEXT,
  "min_length_threshold_percentage_resfinder" TEXT,
  "pointfinder_database_download_date" TEXT,
  "id_threshold_percentage_pointfinder" TEXT,
  "min_length_threshold_percentage_pointfinder" TEXT,
  "resfinder_brief" TEXT,
  "resfinder_detailed" TEXT,
  "class_pheno_table_antibiotics_pheno_table" TEXT,
  "spectinomycin_aminocyclitol" TEXT,
  "unknown aminocyclitol_aminocyclitol" TEXT,
  "amikacin_aminoglycoside" TEXT,
  "apramycin_aminoglycoside" TEXT,
  "arbekacin_aminoglycoside" TEXT,
  "astromicin_aminoglycoside" TEXT,
  "butiromycin_aminoglycoside" TEXT,
  "butirosin_aminoglycoside" TEXT,
  "capreomycin_aminoglycoside" TEXT,
  "dibekacin_aminoglycoside" TEXT,
  "fortimicin_aminoglycoside" TEXT,
  "g418_aminoglycoside" TEXT,
  "gentamicin_aminoglycoside" TEXT,
  "gentamicin c_aminoglycoside" TEXT,
  "hygromycin_aminoglycoside" TEXT,
  "isepamicin_aminoglycoside" TEXT,
  "kanamycin_aminoglycoside" TEXT,
  "kanamycin a_aminoglycoside" TEXT,
  "kasugamycin_aminoglycoside" TEXT,
  "lividomycin_aminoglycoside" TEXT,
  "neomycin_aminoglycoside" TEXT,
  "netilmicin_aminoglycoside" TEXT,
  "paromomycin_aminoglycoside" TEXT,
  "ribostamycin_aminoglycoside" TEXT,
  "sisomicin_aminoglycoside" TEXT,
  "streptomycin_aminoglycoside" TEXT,
  "tobramycin_aminoglycoside" TEXT,
  "unknown aminoglycoside_aminoglycoside" TEXT,
  "chloramphenicol_phenicol" TEXT,
  "florfenicol_phenicol" TEXT,
  "unknown amphenicol_phenicol" TEXT,
  "unknown phenicol_phenicol" TEXT,
  "d-cycloserine_analog of d-alanine" TEXT,
  "unknown analog of d-alanine_analog of d-alanine" TEXT,
  "amoxicillin_beta-lactam" TEXT,
  "amoxicillin+clavulanic acid_beta-lactam" TEXT,
  "ampicillin_beta-lactam" TEXT,
  "ampicillin+clavulanic acid_beta-lactam" TEXT,
  "aztreonam_beta-lactam" TEXT,
  "cefazolin_beta-lactam" TEXT,
  "cefepime_beta-lactam" TEXT,
  "cefixime_beta-lactam" TEXT,
  "cefotaxime_beta-lactam" TEXT,
  "cefotaxime+clavulanic acid_beta-lactam" TEXT,
  "cefoxitin_beta-lactam" TEXT,
  "ceftaroline_beta-lactam" TEXT,
  "ceftazidime_beta-lactam" TEXT,
  "ceftazidime+avibactam_beta-lactam" TEXT,
  "ceftriaxone_beta-lactam" TEXT,
  "cefuroxime_beta-lactam" TEXT,
  "cephalothin_beta-lactam" TEXT,
  "cephalotin_beta-lactam" TEXT,
  "ertapenem_beta-lactam" TEXT,
  "imipenem_beta-lactam" TEXT,
  "meropenem_beta-lactam" TEXT,
  "penicillin_beta-lactam" TEXT,
  "piperacillin_beta-lactam" TEXT,
  "piperacillin+clavulanic acid_beta-lactam" TEXT,
  "piperacillin+tazobactam_beta-lactam" TEXT,
  "temocillin_beta-lactam" TEXT,
  "ticarcillin_beta-lactam" TEXT,
  "ticarcillin+clavulanic acid_beta-lactam" TEXT,
  "unknown beta-lactam_beta-lactam" TEXT,
  "bedaquiline_diarylquinoline" TEXT,
  "unknown diarylquinoline_diarylquinoline" TEXT,
  "sulfamethoxazole_folate pathway antagonist" TEXT,
  "trimethoprim_folate pathway antagonist" TEXT,
  "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
  "fosfomycin_fosfomycin" TEXT,
  "unknown fosfomycin_fosfomycin" TEXT,
  "teicoplanin_glycopeptide" TEXT,
  "vancomycin_glycopeptide" TEXT,
  "unknown glycopeptide_glycopeptide" TEXT,
  "clofazimine_iminophenazine" TEXT,
  "unknown iminophenazine_iminophenazine" TEXT,
  "isoniazid_isonicotinic acid hydrazide" TEXT,
  "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
  "clindamycin_lincosamide" TEXT,
  "lincomycin_lincosamide" TEXT,
  "unknown lincosamide_lincosamide" TEXT,
  "azithromycin_macrolide" TEXT,
  "carbomycin_macrolide" TEXT,
  "erythromycin_macrolide" TEXT,
  "oleandomycin_macrolide" TEXT,
  "spiramycin_macrolide" TEXT,
  "telithromycin_macrolide" TEXT,
  "tylosin_macrolide" TEXT,
  "unknown macrolide_macrolide" TEXT,
  "metronidazole_nitroimidazole" TEXT,
  "unknown nitroimidazole_nitroimidazole" TEXT,
  "linezolid_oxazolidinone" TEXT,
  "unknown oxazolidinone_oxazolidinone" TEXT,
  "tiamulin_pleuromutilin" TEXT,
  "unknown pleuromutilin_pleuromutilin" TEXT,
  "colistin_polymyxin" TEXT,
  "unknown polymyxin_polymyxin" TEXT,
  "mupirocin_pseudomonic acid" TEXT,
  "unknown pseudomonic acid_pseudomonic acid" TEXT,
  "ciprofloxacin_quinolone" TEXT,
  "fluoroquinolone_quinolone" TEXT,
  "nalidixic acid_quinolone" TEXT,
  "unknown quinolone_quinolone" TEXT,
  "unknown fluoroquinolone_quinolone" TEXT,
  "rifampicin_rifamycin" TEXT,
  "unknown rifamycin_rifamycin" TEXT,
  "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
  "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
  "fusidic acid_steroid antibacterial" TEXT,
  "unknown steroid antibacterial_steroid antibacterial" TEXT,
  "dalfopristin_streptogramin a" TEXT,
  "pristinamycin iia_streptogramin a" TEXT,
  "quinupristin+dalfopristin_streptogramin a" TEXT,
  "unknown streptogramin a_streptogramin a" TEXT,
  "virginiamycin m_streptogramin a" TEXT,
  "pristinamycin ia_streptogramin b" TEXT,
  "quinupristin_streptogramin b" TEXT,
  "virginiamycin s_streptogramin b" TEXT,
  "unknown streptogramin b_streptogramin b" TEXT,
  "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
  "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
  "doxycycline_tetracycline" TEXT,
  "minocycline_tetracycline" TEXT,
  "tetracycline_tetracycline" TEXT,
  "tigecycline_tetracycline" TEXT,
  "unknown tetracycline_tetracycline" TEXT,
  "ethionamide_thioamide" TEXT,
  "unknown thioamide_thioamide" TEXT,
  "carbapenem_under_development" TEXT,
  "ceftiofur_under_development" TEXT,
  "cephalosporins_under_development" TEXT,
  "fluoroquinolone_under_development" TEXT,
  "norfloxacin_under_development" TEXT,
  "ethambutol_unspecified" TEXT,
  "unknown unspecified_unspecified" TEXT,
  "class_pheno_table_disinfectants_pheno_table" TEXT,
  "formaldehyde_aldehydes" TEXT,
  "unknown aldehyde_aldehydes" TEXT,
  "temperature_heat" TEXT,
  "hydrogen peroxide_peroxides" TEXT,
  "unknown peroxide_peroxides" TEXT,
  "benzylkonium chloride_quaternary ammonium compounds" TEXT,
  "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
  "chlorhexidine_quaternary ammonium compounds" TEXT,
  "ethidium bromide_quaternary ammonium compounds" TEXT,
  "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
  "#pointfinder" TEXT,
  "ampC_promoter_size_53bp" TEXT,
  "folP" TEXT,
  "gyrA" TEXT,
  "gyrB" TEXT,
  "parC" TEXT,
  "parE" TEXT,
  "pmrA" TEXT,
  "pmrB" TEXT,
  "rpoB" TEXT,
  "16S_rrsB" TEXT,
  "16S_rrsC" TEXT,
  "16S_rrsH" TEXT,
  "23S" TEXT
);

CREATE TABLE amr_report_salmonella( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_filename" TEXT,
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "resfinder_pointfinder_software_version" TEXT,
  "resfinder_database_download_date" TEXT,
  "id_threshold_percentage_resfinder" TEXT,
  "min_length_threshold_percentage_resfinder" TEXT,
  "pointfinder_database_download_date" TEXT,
  "id_threshold_percentage_pointfinder" TEXT,
  "min_length_threshold_percentage_pointfinder" TEXT,
  "resfinder_brief" TEXT,
  "resfinder_detailed" TEXT,
  "class_pheno_table_antibiotics_pheno_table" TEXT,
  "spectinomycin_aminocyclitol" TEXT,
  "unknown aminocyclitol_aminocyclitol" TEXT,
  "amikacin_aminoglycoside" TEXT,
  "apramycin_aminoglycoside" TEXT,
  "arbekacin_aminoglycoside" TEXT,
  "astromicin_aminoglycoside" TEXT,
  "butiromycin_aminoglycoside" TEXT,
  "butirosin_aminoglycoside" TEXT,
  "capreomycin_aminoglycoside" TEXT,
  "dibekacin_aminoglycoside" TEXT,
  "fortimicin_aminoglycoside" TEXT,
  "g418_aminoglycoside" TEXT,
  "gentamicin_aminoglycoside" TEXT,
  "gentamicin c_aminoglycoside" TEXT,
  "hygromycin_aminoglycoside" TEXT,
  "isepamicin_aminoglycoside" TEXT,
  "kanamycin_aminoglycoside" TEXT,
  "kanamycin a_aminoglycoside" TEXT,
  "kasugamycin_aminoglycoside" TEXT,
  "lividomycin_aminoglycoside" TEXT,
  "neomycin_aminoglycoside" TEXT,
  "netilmicin_aminoglycoside" TEXT,
  "paromomycin_aminoglycoside" TEXT,
  "ribostamycin_aminoglycoside" TEXT,
  "sisomicin_aminoglycoside" TEXT,
  "streptomycin_aminoglycoside" TEXT,
  "tobramycin_aminoglycoside" TEXT,
  "unknown aminoglycoside_aminoglycoside" TEXT,
  "chloramphenicol_phenicol" TEXT,
  "florfenicol_phenicol" TEXT,
  "unknown amphenicol_phenicol" TEXT,
  "unknown phenicol_phenicol" TEXT,
  "d-cycloserine_analog of d-alanine" TEXT,
  "unknown analog of d-alanine_analog of d-alanine" TEXT,
  "amoxicillin_beta-lactam" TEXT,
  "amoxicillin+clavulanic acid_beta-lactam" TEXT,
  "ampicillin_beta-lactam" TEXT,
  "ampicillin+clavulanic acid_beta-lactam" TEXT,
  "aztreonam_beta-lactam" TEXT,
  "cefazolin_beta-lactam" TEXT,
  "cefepime_beta-lactam" TEXT,
  "cefixime_beta-lactam" TEXT,
  "cefotaxime_beta-lactam" TEXT,
  "cefotaxime+clavulanic acid_beta-lactam" TEXT,
  "cefoxitin_beta-lactam" TEXT,
  "ceftaroline_beta-lactam" TEXT,
  "ceftazidime_beta-lactam" TEXT,
  "ceftazidime+avibactam_beta-lactam" TEXT,
  "ceftriaxone_beta-lactam" TEXT,
  "cefuroxime_beta-lactam" TEXT,
  "cephalothin_beta-lactam" TEXT,
  "cephalotin_beta-lactam" TEXT,
  "ertapenem_beta-lactam" TEXT,
  "imipenem_beta-lactam" TEXT,
  "meropenem_beta-lactam" TEXT,
  "penicillin_beta-lactam" TEXT,
  "piperacillin_beta-lactam" TEXT,
  "piperacillin+clavulanic acid_beta-lactam" TEXT,
  "piperacillin+tazobactam_beta-lactam" TEXT,
  "temocillin_beta-lactam" TEXT,
  "ticarcillin_beta-lactam" TEXT,
  "ticarcillin+clavulanic acid_beta-lactam" TEXT,
  "unknown beta-lactam_beta-lactam" TEXT,
  "bedaquiline_diarylquinoline" TEXT,
  "unknown diarylquinoline_diarylquinoline" TEXT,
  "sulfamethoxazole_folate pathway antagonist" TEXT,
  "trimethoprim_folate pathway antagonist" TEXT,
  "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
  "fosfomycin_fosfomycin" TEXT,
  "unknown fosfomycin_fosfomycin" TEXT,
  "teicoplanin_glycopeptide" TEXT,
  "vancomycin_glycopeptide" TEXT,
  "unknown glycopeptide_glycopeptide" TEXT,
  "clofazimine_iminophenazine" TEXT,
  "unknown iminophenazine_iminophenazine" TEXT,
  "isoniazid_isonicotinic acid hydrazide" TEXT,
  "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
  "clindamycin_lincosamide" TEXT,
  "lincomycin_lincosamide" TEXT,
  "unknown lincosamide_lincosamide" TEXT,
  "azithromycin_macrolide" TEXT,
  "carbomycin_macrolide" TEXT,
  "erythromycin_macrolide" TEXT,
  "oleandomycin_macrolide" TEXT,
  "spiramycin_macrolide" TEXT,
  "telithromycin_macrolide" TEXT,
  "tylosin_macrolide" TEXT,
  "unknown macrolide_macrolide" TEXT,
  "metronidazole_nitroimidazole" TEXT,
  "unknown nitroimidazole_nitroimidazole" TEXT,
  "linezolid_oxazolidinone" TEXT,
  "unknown oxazolidinone_oxazolidinone" TEXT,
  "tiamulin_pleuromutilin" TEXT,
  "unknown pleuromutilin_pleuromutilin" TEXT,
  "colistin_polymyxin" TEXT,
  "unknown polymyxin_polymyxin" TEXT,
  "mupirocin_pseudomonic acid" TEXT,
  "unknown pseudomonic acid_pseudomonic acid" TEXT,
  "ciprofloxacin_quinolone" TEXT,
  "fluoroquinolone_quinolone" TEXT,
  "nalidixic acid_quinolone" TEXT,
  "unknown quinolone_quinolone" TEXT,
  "unknown fluoroquinolone_quinolone" TEXT,
  "rifampicin_rifamycin" TEXT,
  "unknown rifamycin_rifamycin" TEXT,
  "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
  "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
  "fusidic acid_steroid antibacterial" TEXT,
  "unknown steroid antibacterial_steroid antibacterial" TEXT,
  "dalfopristin_streptogramin a" TEXT,
  "pristinamycin iia_streptogramin a" TEXT,
  "quinupristin+dalfopristin_streptogramin a" TEXT,
  "unknown streptogramin a_streptogramin a" TEXT,
  "virginiamycin m_streptogramin a" TEXT,
  "pristinamycin ia_streptogramin b" TEXT,
  "quinupristin_streptogramin b" TEXT,
  "virginiamycin s_streptogramin b" TEXT,
  "unknown streptogramin b_streptogramin b" TEXT,
  "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
  "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
  "doxycycline_tetracycline" TEXT,
  "minocycline_tetracycline" TEXT,
  "tetracycline_tetracycline" TEXT,
  "tigecycline_tetracycline" TEXT,
  "unknown tetracycline_tetracycline" TEXT,
  "ethionamide_thioamide" TEXT,
  "unknown thioamide_thioamide" TEXT,
  "carbapenem_under_development" TEXT,
  "ceftiofur_under_development" TEXT,
  "cephalosporins_under_development" TEXT,
  "fluoroquinolone_under_development" TEXT,
  "norfloxacin_under_development" TEXT,
  "ethambutol_unspecified" TEXT,
  "unknown unspecified_unspecified" TEXT,
  "class_pheno_table_disinfectants_pheno_table" TEXT,
  "formaldehyde_aldehydes" TEXT,
  "unknown aldehyde_aldehydes" TEXT,
  "temperature_heat" TEXT,
  "hydrogen peroxide_peroxides" TEXT,
  "unknown peroxide_peroxides" TEXT,
  "benzylkonium chloride_quaternary ammonium compounds" TEXT,
  "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
  "chlorhexidine_quaternary ammonium compounds" TEXT,
  "ethidium bromide_quaternary ammonium compounds" TEXT,
  "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
  "#pointfinder" TEXT,
  "ampC_promoter_size_53bp" TEXT,
  "folP" TEXT,
  "gyrA" TEXT,
  "gyrB" TEXT,
  "parC" TEXT,
  "parE" TEXT,
  "pmrA" TEXT,
  "pmrB" TEXT,
  "rpoB" TEXT,
  "16S_rrsB" TEXT,
  "16S_rrsC" TEXT,
  "16S_rrsH" TEXT,
  "23S" TEXT,
  "16S_rrsD" TEXT,
  "acrB" TEXT
);

CREATE TABLE amr_report_yersinia( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_filename" TEXT,
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "resfinder_pointfinder_software_version" TEXT,
  "resfinder_database_download_date" TEXT,
  "id_threshold_percentage_resfinder" TEXT,
  "min_length_threshold_percentage_resfinder" TEXT,
  "pointfinder_database_download_date" TEXT,
  "id_threshold_percentage_pointfinder" TEXT,
  "min_length_threshold_percentage_pointfinder" TEXT,
  "resfinder_brief" TEXT,
  "resfinder_detailed" TEXT,
  "class_pheno_table_antibiotics_pheno_table" TEXT,
  "spectinomycin_aminocyclitol" TEXT,
  "unknown aminocyclitol_aminocyclitol" TEXT,
  "amikacin_aminoglycoside" TEXT,
  "apramycin_aminoglycoside" TEXT,
  "arbekacin_aminoglycoside" TEXT,
  "astromicin_aminoglycoside" TEXT,
  "butiromycin_aminoglycoside" TEXT,
  "butirosin_aminoglycoside" TEXT,
  "capreomycin_aminoglycoside" TEXT,
  "dibekacin_aminoglycoside" TEXT,
  "fortimicin_aminoglycoside" TEXT,
  "g418_aminoglycoside" TEXT,
  "gentamicin_aminoglycoside" TEXT,
  "gentamicin c_aminoglycoside" TEXT,
  "hygromycin_aminoglycoside" TEXT,
  "isepamicin_aminoglycoside" TEXT,
  "kanamycin_aminoglycoside" TEXT,
  "kanamycin a_aminoglycoside" TEXT,
  "kasugamycin_aminoglycoside" TEXT,
  "lividomycin_aminoglycoside" TEXT,
  "neomycin_aminoglycoside" TEXT,
  "netilmicin_aminoglycoside" TEXT,
  "paromomycin_aminoglycoside" TEXT,
  "ribostamycin_aminoglycoside" TEXT,
  "sisomicin_aminoglycoside" TEXT,
  "streptomycin_aminoglycoside" TEXT,
  "tobramycin_aminoglycoside" TEXT,
  "unknown aminoglycoside_aminoglycoside" TEXT,
  "chloramphenicol_phenicol" TEXT,
  "florfenicol_phenicol" TEXT,
  "unknown amphenicol_phenicol" TEXT,
  "unknown phenicol_phenicol" TEXT,
  "d-cycloserine_analog of d-alanine" TEXT,
  "unknown analog of d-alanine_analog of d-alanine" TEXT,
  "amoxicillin_beta-lactam" TEXT,
  "amoxicillin+clavulanic acid_beta-lactam" TEXT,
  "ampicillin_beta-lactam" TEXT,
  "ampicillin+clavulanic acid_beta-lactam" TEXT,
  "aztreonam_beta-lactam" TEXT,
  "cefazolin_beta-lactam" TEXT,
  "cefepime_beta-lactam" TEXT,
  "cefixime_beta-lactam" TEXT,
  "cefotaxime_beta-lactam" TEXT,
  "cefotaxime+clavulanic acid_beta-lactam" TEXT,
  "cefoxitin_beta-lactam" TEXT,
  "ceftaroline_beta-lactam" TEXT,
  "ceftazidime_beta-lactam" TEXT,
  "ceftazidime+avibactam_beta-lactam" TEXT,
  "ceftriaxone_beta-lactam" TEXT,
  "cefuroxime_beta-lactam" TEXT,
  "cephalothin_beta-lactam" TEXT,
  "cephalotin_beta-lactam" TEXT,
  "ertapenem_beta-lactam" TEXT,
  "imipenem_beta-lactam" TEXT,
  "meropenem_beta-lactam" TEXT,
  "penicillin_beta-lactam" TEXT,
  "piperacillin_beta-lactam" TEXT,
  "piperacillin+clavulanic acid_beta-lactam" TEXT,
  "piperacillin+tazobactam_beta-lactam" TEXT,
  "temocillin_beta-lactam" TEXT,
  "ticarcillin_beta-lactam" TEXT,
  "ticarcillin+clavulanic acid_beta-lactam" TEXT,
  "unknown beta-lactam_beta-lactam" TEXT,
  "bedaquiline_diarylquinoline" TEXT,
  "unknown diarylquinoline_diarylquinoline" TEXT,
  "sulfamethoxazole_folate pathway antagonist" TEXT,
  "trimethoprim_folate pathway antagonist" TEXT,
  "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
  "fosfomycin_fosfomycin" TEXT,
  "unknown fosfomycin_fosfomycin" TEXT,
  "teicoplanin_glycopeptide" TEXT,
  "vancomycin_glycopeptide" TEXT,
  "unknown glycopeptide_glycopeptide" TEXT,
  "clofazimine_iminophenazine" TEXT,
  "unknown iminophenazine_iminophenazine" TEXT,
  "isoniazid_isonicotinic acid hydrazide" TEXT,
  "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
  "clindamycin_lincosamide" TEXT,
  "lincomycin_lincosamide" TEXT,
  "unknown lincosamide_lincosamide" TEXT,
  "azithromycin_macrolide" TEXT,
  "carbomycin_macrolide" TEXT,
  "erythromycin_macrolide" TEXT,
  "oleandomycin_macrolide" TEXT,
  "spiramycin_macrolide" TEXT,
  "telithromycin_macrolide" TEXT,
  "tylosin_macrolide" TEXT,
  "unknown macrolide_macrolide" TEXT,
  "metronidazole_nitroimidazole" TEXT,
  "unknown nitroimidazole_nitroimidazole" TEXT,
  "linezolid_oxazolidinone" TEXT,
  "unknown oxazolidinone_oxazolidinone" TEXT,
  "tiamulin_pleuromutilin" TEXT,
  "unknown pleuromutilin_pleuromutilin" TEXT,
  "colistin_polymyxin" TEXT,
  "unknown polymyxin_polymyxin" TEXT,
  "mupirocin_pseudomonic acid" TEXT,
  "unknown pseudomonic acid_pseudomonic acid" TEXT,
  "ciprofloxacin_quinolone" TEXT,
  "fluoroquinolone_quinolone" TEXT,
  "nalidixic acid_quinolone" TEXT,
  "unknown quinolone_quinolone" TEXT,
  "unknown fluoroquinolone_quinolone" TEXT,
  "rifampicin_rifamycin" TEXT,
  "unknown rifamycin_rifamycin" TEXT,
  "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
  "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
  "fusidic acid_steroid antibacterial" TEXT,
  "unknown steroid antibacterial_steroid antibacterial" TEXT,
  "dalfopristin_streptogramin a" TEXT,
  "pristinamycin iia_streptogramin a" TEXT,
  "quinupristin+dalfopristin_streptogramin a" TEXT,
  "unknown streptogramin a_streptogramin a" TEXT,
  "virginiamycin m_streptogramin a" TEXT,
  "pristinamycin ia_streptogramin b" TEXT,
  "quinupristin_streptogramin b" TEXT,
  "virginiamycin s_streptogramin b" TEXT,
  "unknown streptogramin b_streptogramin b" TEXT,
  "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
  "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
  "doxycycline_tetracycline" TEXT,
  "minocycline_tetracycline" TEXT,
  "tetracycline_tetracycline" TEXT,
  "tigecycline_tetracycline" TEXT,
  "unknown tetracycline_tetracycline" TEXT,
  "ethionamide_thioamide" TEXT,
  "unknown thioamide_thioamide" TEXT,
  "carbapenem_under_development" TEXT,
  "ceftiofur_under_development" TEXT,
  "cephalosporins_under_development" TEXT,
  "fluoroquinolone_under_development" TEXT,
  "norfloxacin_under_development" TEXT,
  "ethambutol_unspecified" TEXT,
  "unknown unspecified_unspecified" TEXT,
  "class_pheno_table_disinfectants_pheno_table" TEXT,
  "formaldehyde_aldehydes" TEXT,
  "unknown aldehyde_aldehydes" TEXT,
  "temperature_heat" TEXT,
  "hydrogen peroxide_peroxides" TEXT,
  "unknown peroxide_peroxides" TEXT,
  "benzylkonium chloride_quaternary ammonium compounds" TEXT,
  "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
  "chlorhexidine_quaternary ammonium compounds" TEXT,
  "ethidium bromide_quaternary ammonium compounds" TEXT,
  "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
  "#pointfinder" TEXT,
  "ampC_promoter_size_53bp" TEXT,
  "folP" TEXT,
  "gyrA" TEXT,
  "gyrB" TEXT,
  "parC" TEXT,
  "parE" TEXT,
  "pmrA" TEXT,
  "pmrB" TEXT,
  "rpoB" TEXT,
  "16S_rrsB" TEXT,
  "16S_rrsC" TEXT,
  "16S_rrsH" TEXT,
  "23S" TEXT
);
