
CREATE TABLE typing_report_campy(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "pathotype" TEXT,
  "pathotype_genes_present" TEXT,
  "serotypefinder_software_version" TEXT,
  "serotypefinder_database_version" TEXT,
  "id_threshold_percentage_serotypefinder" TEXT,
  "min_length_threshold_percentage_serotypefinder" TEXT,
  "O_type_serotypefinder" TEXT,
  "H_type_serotypefinder" TEXT,
  "O_type_serotypefinder_long" TEXT,
  "H_type_serotypefinder_long" TEXT,
  "Min_coverage_virulencefinder" TEXT,
  "Min_threshold_identity_virulencefinder" TEXT
);

CREATE TABLE typing_report_ecoli(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),  
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "pathotype" TEXT,
  "pathotype_genes_present" TEXT,
  "serotypefinder_software_version" TEXT,
  "serotypefinder_database_version" TEXT,
  "id_threshold_percentage_serotypefinder" TEXT,
  "min_length_threshold_percentage_serotypefinder" TEXT,
  "O_type_serotypefinder" TEXT,
  "H_type_serotypefinder" TEXT,
  "O_type_serotypefinder_long" TEXT,
  "H_type_serotypefinder_long" TEXT,
  "Min_coverage_virulencefinder" TEXT,
  "Min_threshold_identity_virulencefinder" TEXT,
  "stx1_subtype_virulencefinder" TEXT,
  "stx2_subtype_virulencefinder" TEXT,
  "eae_virulencefinder" TEXT,
  "aggR_virulencefinder" TEXT,
  "who_risk_level_virulencefinder" TEXT,
  "aafA:AAF/II major fimbrial subunit" TEXT,
  "aafB:AAF/II minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "aafC:Usher, AAF/II assembly unit" TEXT,
  "aafD:Chaperone, AAF/II assembly unit" TEXT,
  "aaiC:Type VI secretion protein" TEXT,
  "aalF:CS23 Minor structural subunit" TEXT,
  "aalG:CS23 Minor structural subunit" TEXT,
  "aap:Dispersin, antiaggregation protein" TEXT,
  "aar:AggR-activated regulator" TEXT,
  "aatA:Dispersin transporter protein" TEXT,
  "afaA:Transcriptional regulator" TEXT,
  "afaB:Periplasmic chaperone" TEXT,
  "afaC:Outer membrane usher protein" TEXT,
  "afaD:Afimbrial adhesion" TEXT,
  "afaE:Adhesin protein" TEXT,
  "afaE8" TEXT,
  "agg3A:AAF/III major fimbrial subunit" TEXT,
  "agg3B:AAF/III minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "agg3C:Usher, AAF/III assembly unit" TEXT,
  "agg3D:Chaperone, AAF/III assembly unit" TEXT,
  "agg4A:AAF/IV major fimbrial subunit" TEXT,
  "agg4B:AAF/IV minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "agg4C:Usher, AAF/IV assembly unit" TEXT,
  "agg4D:Chaperone, AAF/IV assembly unit" TEXT,
  "agg5A" TEXT,
  "aggA:AAF/I major fimbrial subunit" TEXT,
  "aggB:AAF/I minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "aggC:Usher, AAF/I assembly unit" TEXT,
  "aggD:Chaperone, AAF/I assembly unit" TEXT,
  "aggR:AraC transcriptional activator" TEXT,
  "air:Enteroaggregative immunoglobulin repeat protein" TEXT,
  "anr:AraC negative regulator" TEXT,
  "astA:Heat-stable enterotoxin 1, astA:EAST-1 heat-stable toxin" TEXT,
  "astA:Heat-stable enterotoxin EAST-1" TEXT,
  "bfpA:Major subunit of bundle-forming pili" TEXT,
  "capU:Hexosyltransferase homolog" TEXT,
  "cba:Colicin B" TEXT,
  "ccI:Cloacin" TEXT,
  "cdtB:Cytolethal distending toxin B" TEXT,
  "cea:Colicin E1" TEXT,
  "celb:Endonuclease colicin E2" TEXT,
  "cfaC" TEXT,
  "chuA:Outer membrane hemin receptor" TEXT,
  "cia:Colicin ia" TEXT,
  "cib:Colicin ib" TEXT,
  "cif:Type III secreted effector" TEXT,
  "clbB:Hybrid non-ribosomal peptide / polyketide megasynthase" TEXT,
  "colE2:Colicin E2" TEXT,
  "colE2-like:Colicin lysis protein precursor E2-like" TEXT,
  "colE8:Colicin E8" TEXT,
  "csgA:curlin major subunit CsgA" TEXT,
  "cma:Colicin M" TEXT,
  "cma:Colicin M activity" TEXT,
  "cnf1:Cytotoxic necrotizing factor" TEXT,
  "cofA:Longus type IV pilus subunit" TEXT,
  "cvaC:Microcin C" TEXT,
  "eae:Intimin" TEXT,
  "eae-b01a-beta:" TEXT,
  "eae-a01-alpha:Intimin-a01-alpha" TEXT,
  "eae-a02-alpha:Intimin-a02-alpha" TEXT,
  "eae-a03-zeta:Intimin-a03-zeta" TEXT,
  "eae-a04-zeta:Intimin-a04-zeta" TEXT,
  "eae-a05a-nu:Intimin-a05a-nu" TEXT,
  "eae-a05b-nu:Intimin-a05b-nu" TEXT,
  "eae-a06-omicron:Intimin-a06-omicron" TEXT,
  "eae-a07-tau:Intimin-a07-tau" TEXT,
  "eae-a08-alpha:Intimin-a08-alpha" TEXT,
  "eae-a09-alpha:Intimin-a09-alpha" TEXT,
  "eae-a10-alpha:Intimin-a10-alpha" TEXT,
  "eae-a11-alpha:Intimin-a11-alpha" TEXT,
  "eae-a12-alpha:Intimin-a12-alpha" TEXT,
  "eae-a13a-alpha:Intimin-a13a-alpha" TEXT,
  "eae-a13b-alpha:Intimin-a13b-alpha" TEXT,
  "eae-a14-alpha:Intimin-a14-alpha" TEXT,
  "eae-a15-alpha:Intimin-a15-alpha" TEXT,
  "eae-a16-alpha:Intimin-a16-alpha" TEXT,
  "eae-a17-alpha:Intimin-a17-alpha" TEXT,
  "eae-a18-alpha:Intimin-a18-alpha" TEXT,
  "eae-b01a-beta:Intimin-b01a-beta" TEXT,
  "eae-b01b-beta:Intimin-b01b-beta" TEXT,
  "eae-b02a-beta:Intimin-b02a-beta" TEXT,
  "eae-b02b-beta:Intimin-b02b-beta" TEXT,
  "eae-b03-beta:Intimin-b03-beta" TEXT,
  "eae-b04-delta:Intimin-b04-delta" TEXT,
  "eae-b05-Citrobacter:Intimin-b05-Citrobacter" TEXT,
  "eae-b06-beta:Intimin-b06-beta" TEXT,
  "eae-b07-beta:Intimin-b07-beta" TEXT,
  "eae-b08-kappa:Intimin-b08-kappa" TEXT,
  "eae-e01-epsilon:Intimin-e01-epsilon" TEXT,
  "eae-e02-epsilon:Intimin-e02-epsilon" TEXT,
  "eae-e03a-epsilon:Intimin-e03a-epsilon" TEXT,
  "eae-e03b-epsilon:Intimin-e03b-epsilon" TEXT,
  "eae-e04-epsilon:Intimin-e04-epsilon" TEXT,
  "eae-e05-eta:Intimin-e05-eta" TEXT,
  "eae-e06-eta:Intimin-e06-eta" TEXT,
  "eae-e07-xi:Intimin-e07-xi" TEXT,
  "eae-e08-pi:Intimin-e08-pi" TEXT,
  "eae-e09-epsilon:Intimin-e09-epsilon" TEXT,
  "eae-e10-epsilon:Intimin-e10-epsilon" TEXT,
  "eae-e11-epsilon:Intimin-e11-epsilon" TEXT,
  "eae-e12-eta:Intimin-e12-eta" TEXT,
  "eae-g01-gamma:Intimin-g01-gamma" TEXT,
  "eae-g02-theta:Intimin-g02-theta" TEXT,
  "eae-g03-mu:Intimin-g03-mu" TEXT,
  "eae-g04-sigma:Intimin-g04-sigma" TEXT,
  "eae-g05-gamma:Intimin-g05-gamma" TEXT,
  "eae-g06-gamma:Intimin-g06-gamma" TEXT,
  "eae-g07-gamma:Intimin-g07-gamma" TEXT,
  "eae-g08-gamma:Intimin-g08-gamma" TEXT,
  "eae-g09-gamma:Intimin-g09-gamma" TEXT,
  "eae-i01-iota:Intimin-i01-iota" TEXT,
  "eae-i02b-iota:Intimin-i02b-iota" TEXT,
  "eae-i03-upsilon:Intimin-i03-upsilon" TEXT,
  "eae-l01-lambda:Intimin-l01-lambda" TEXT,
  "eae-l02-lambda:Intimin-l02-lambda" TEXT,
  "eae-l03-lambda:Intimin-l03-lambda" TEXT,
  "eae-l04a-lambda:Intimin-l04a-lambda" TEXT,
  "eae-l04b-lambda:Intimin-l04b-lambda" TEXT,
  "eae-l05-lambda:Intimin-l05-lambda" TEXT,
  "eae-r01-rho:Intimin-r01-rho" TEXT,
  "eae-r02-rho:Intimin-r02-rho" TEXT,
  "eae-r03-rho:Intimin-r03-rho" TEXT,
  "eae-r04-rho:Intimin-r04-rho" TEXT,
  "eatA:enterotoxigenic E. coli (ETEC) autotransporter A" TEXT,
  "eatA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "efa1:EHEC factor for adherence; lymphostatin Efa1-LifA" TEXT,
  "ehxA:Enterohaemolysin" TEXT,
  "eilA:Salmonella HilA homolog" TEXT,
  "eltIAB-1:Heat-labile enterotoxin LTIh-1" TEXT,
  "eltIAB-2:Heat-labile enterotoxin LTIh-2" TEXT,
  "eltIAB-3:Heat-labile enterotoxin LTIh-3" TEXT,
  "eltIAB-4:Heat-labile enterotoxin LTIh-4" TEXT,
  "eltIAB-5:Heat-labile enterotoxin LTIh-5" TEXT,
  "eltIAB-6:Heat-labile enterotoxin LTIh-6" TEXT,
  "eltIAB-7:Heat-labile enterotoxin LTIh-7" TEXT,
  "eltIAB-8:Heat-labile enterotoxin LTIh-8" TEXT,
  "eltIAB-9:Heat-labile enterotoxin LTIh9" TEXT,
  "eltIAB-10:Heat-labile enterotoxin LTIh-10" TEXT,
  "eltIAB-11:Heat-labile enterotoxin LTIh-11" TEXT,
  "eltIAB-12:Heat-labile enterotoxin LTIh-12" TEXT,
  "eltIAB-13:Heat-labile enterotoxin LTIh-13" TEXT,
  "eltIAB-14:Heat-labile enterotoxin LTIh-14" TEXT,
  "eltIAB-15:Heat-labile enterotoxin LTIh-15" TEXT,
  "eltIAB-15b:Heat-labile enterotoxin LTIh-15b" TEXT,
  "eltIAB-16:Heat-labile enterotoxin LTIh-16" TEXT,
  "eltIAB-17:Heat-labile enterotoxin LTIh-17" TEXT,
  "eltIAB-18:Heat-labile enterotoxin LTIh-18" TEXT,
  "eltIAB-19:Heat-labile enterotoxin LTIh-19" TEXT,
  "eltIAB-20:Heat-labile enterotoxin LTIh-20" TEXT,
  "eltIAB-21:Heat-labile enterotoxin LTIh-21" TEXT,
  "eltIAB-22:Heat-labile enterotoxin LTIh-22" TEXT,
  "eltIAB-23:Heat-labile enterotoxin LTIh-23" TEXT,
  "eltIAB-24:Heat-labile enterotoxin LTIh-24" TEXT,
  "eltIAB-25:Heat-labile enterotoxin LTIh-25" TEXT,
  "eltIAB-26:Heat-labile enterotoxin LTIh-26" TEXT,
  "eltIAB-27:Heat-labile enterotoxin LTIh-27" TEXT,
  "eltIAB-28:Heat-labile enterotoxin LTIh-28" TEXT,
  "eltIAB-29:Heat-labile enterotoxin LTIh-29" TEXT,
  "eltIAB-30:Heat-labile enterotoxin LTIh-30" TEXT,
  "eltIAB-31:Heat-labile enterotoxin LTIh-31" TEXT,
  "eltIAB-33:Heat-labile enterotoxin LTIh-32" TEXT,
  "eltIAB-33:Heat-labile enterotoxin LTIh-33" TEXT,
  "eltIIAB-a:Heat-labile enterotoxin LTII-a" TEXT,
  "eltIIAB-b1:Heat-labile enterotoxin LTII-b1" TEXT,
  "eltIIAB-b2:Heat-labile enterotoxin LTII-b2" TEXT,
  "eltIIAB-c1:Heat-labile enterotoxin LTII-c1" TEXT,
  "eltIIAB-c2:Heat-labile enterotoxin LTII-c2" TEXT,
  "eltIIAB-c3:Heat-labile enterotoxin LTII-c3" TEXT,
  "eltIIAB-c4:Heat-labile enterotoxin LTII-c4" TEXT,
  "eltIIAB-c5:Heat-labile enterotoxin LTII-c5" TEXT,
  "eltIIAB-c6:Heat-labile enterotoxin LTII-c6" TEXT,
  "eltIIAB-c7:Heat-labile enterotoxin LTII-c7" TEXT,
  "eltIIAB-c8:Heat-labile enterotoxin LTII-c8" TEXT,
  "eltIIAB-c9:Heat-labile enterotoxin LTII-c9" TEXT,
  "eltIIAB-d1:Heat-labile enterotoxin LTII-d1" TEXT,
  "eltIIAB-d2:Heat-labile enterotoxin LTII-d2" TEXT,
  "eltIIAB-e:Heat-labile enterotoxin LTII-e" TEXT,
  "epeA:enterohemorrhagic E. coli EHEC plasmid-encoded autotransporter" TEXT,
  "epeA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espA:Type III secretions system" TEXT,
  "espB:Secreted protein B" TEXT,
  "espC:EPEC secreted protein C" TEXT,
  "espC:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espF:EPEC secreted protein F; Type III secretion system" TEXT,
  "espI:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espJ:Prophage-encoded type III secretion system effector" TEXT,
  "espP:Extracellular serine protease plasmid-encoded" TEXT,
  "espP:Putative exoprotein precursor" TEXT,
  "espP:Serine protease autotransporter EspP" TEXT,
  "estap-STa1:Heat-stable enterotoxin STa1 porcine variant" TEXT,
  "estah-STa2:Heat-stable enterotoxin STa2 human variant" TEXT,
  "estah-STa3:Heat-stable enterotoxin STa3 human variant" TEXT,
  "estap-STa4:Heat-stable enterotoxin STa4 porcine variant" TEXT,
  "estap-STa5:Heat-stable enterotoxin STa5 porcine variant" TEXT,
  "estap-STa6:Heat-stable enterotoxin STa6 porcine variant" TEXT,
  "estap-STa7:Heat-stable enterotoxin STa7 porcine variant" TEXT,
  "estap-STa8:Heat-stable enterotoxin STa8 porcine variant" TEXT,
  "estap-STa9:Heat-stable enterotoxin STa9 porcine variant" TEXT,
  "estb-STb1:Heat-stable enterotoxin STb1 porcine variant" TEXT,
  "estb-STb2:Heat-stable enterotoxin STb2 human variant" TEXT,
  "etpD:Type II secretion protein" TEXT,
  "etsC:Putative type I secretion outer membrane protein" TEXT,
  "f17A" TEXT,
  "f17G" TEXT,
  "faeC:F4 (K88) Minor fimbrial subunits" TEXT,
  "faeD:F4 (K88) Usher" TEXT,
  "faeF:F4 (K88) Minor fimbrial subunit" TEXT,
  "faeJ:F4 (K88) Fimbria minor subunit" TEXT,
  "fanA:Involved in biogenesis of K99/F5 fimbriae" TEXT,
  "fasA:Fimbriae 987P/F6 subunit" TEXT,
  "fdeC:intimin-like adhesin FdeC" TEXT,
  "fedA:Fimbrial protein F107 subunit A" TEXT,
  "fedF:Fimbrial adhesin AC precursor" TEXT,
  "fimH:Type 1 fimbriae" TEXT,
  "fim41a:Mature Fim41a/F41 protein" TEXT,
  "focC:S fimbrial/F1C minor subunit" TEXT,
  "focCsfaE" TEXT,
  "focG:F1C adhesion" TEXT,
  "focI:S fimbrial/F1C minor subunit" TEXT,
  "fyuA:Siderophore receptor" TEXT,
  "gad:Glutamate decarboxylase" TEXT,
  "hha:hemolysin expression modulator Hha (previous rmoA)" TEXT,
  "hlyE:Avian E. coli haemolysin" TEXT,
  "hlyF:Hemolysin F" TEXT,
  "hra:Heat-resistant agglutinin" TEXT,
  "ibeA:Invasin of brain endothelial cells" TEXT,
  "iha:Adherence protein" TEXT,
  "ipaD:Invasion protein Shigella flexneri" TEXT,
  "ipaH9.8:Invasion plasmid antigen" TEXT,
  "ireA:Siderophore receptor" TEXT,
  "iroN:Enterobactin siderophore receptor protein" TEXT,
  "irp2:High molecular weight protein 2 non-ribosomal peptide synthetase" TEXT,
  "iss:Increased serum survival" TEXT,
  "iucC:Aerobactin synthetase" TEXT,
  "iutA:Ferric aerobactin receptor" TEXT,
  "K88ab:K88/F4 protein subunit" TEXT,
  "katP:Plasmid-encoded catalase peroxidase" TEXT,
  "kpsE:Capsule polysaccharide export inner-membrane protein" TEXT,
  "kpsM:Polysialic acid transport protein" TEXT,
  "kpsM_K11:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsM_K15:Polysialic acid transport protein; Group 3 capsule" TEXT,
  "kpsM_K19:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsM_K19K23:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMII:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K1:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K23:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K24:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K4:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K5:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K52:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K94:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMIII:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K10:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K96:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K98:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "lngA:Longus type IV pilus" TEXT,
  "lpfA:Long polar fimbriae" TEXT,
  "ltcA:Heat-labile enterotoxin A subunit" TEXT,
  "mcbA:Bacteriocin microcin B17" TEXT,
  "mchB:Microcin H47 part of colicin H" TEXT,
  "mchC:MchC protein" TEXT,
  "mchF:ABC transporter protein MchF" TEXT,
  "mcmA:Microcin M part of colicin H" TEXT,
  "neuC:Polysialic acid capsule biosynthesis protein" TEXT,
  "nfaE:Diffuse adherence fibrillar adhesin gene" TEXT,
  "nleA:Non-LEE encoded effector A" TEXT,
  "nleB:Non-LEE encoded effector B" TEXT,
  "nleC:Non-LEE encoded effector C" TEXT,
  "nlpI:lipoprotein NlpI precursor" TEXT,
  "ompT:Outer membrane protease (protein protease 7)" TEXT,
  "ORF3:Isoprenoid Biosynthesis" TEXT,
  "ORF4:Putative isopentenyl-diphosphate delta-isomerase" TEXT,
  "papA_F11:Major pilin subunit F11" TEXT,
  "papA_F12:Major pilin subunit F12" TEXT,
  "papA_F13:Major pilin subunit F13" TEXT,
  "papA_F14:Major pilin subunit F14" TEXT,
  "papA_F1651A:Major pilin subunit F1651A" TEXT,
  "papA_F19:Major pilin subunit F19" TEXT,
  "papA_F20:Major pilin subunit F20" TEXT,
  "papA_F40:Major pilin subunit F40" TEXT,
  "papA_F43:Major pilin subunit F43" TEXT,
  "papA_F48:Major pilin subunit F48" TEXT,
  "papA_F536:Major pilin subunit F536" TEXT,
  "papA_F7-1:Major pilin subunit F7-1" TEXT,
  "papA_F7-2:Major pilin subunit F7-2" TEXT,
  "papA_F8:Major pilin subunit F8" TEXT,
  "papA_F9:Major pilin subunit F9" TEXT,
  "papA_feiA_F8:Major pilin subunit F8" TEXT,
  "papA_ffiA_F15:Major pilin subunit F15" TEXT,
  "papA_ffoA_F14:Major pilin subunit F14" TEXT,
  "papA_fsiA_F16:Major pilin subunit F16" TEXT,
  "papA_fteA_F10:Major pilin subunit F10" TEXT,
  "papA_prsA_F12:Major pilin subunit F12" TEXT,
  "papC:Outer membrane usher P fimbriae" TEXT,
  "perA:EPEC adherence factor" TEXT,
  "pet:Plasmid-encoded toxin, pet:Autotransporter enterotoxin" TEXT,
  "pic:Protease involved in intestinal colonization" TEXT,
  "pic:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "rpeA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "saa:Auto agglutinating adhesin" TEXT,
  "sat:Secreted autotransporter toxin" TEXT,
  "sat:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "senB:Plasmid-encoded enterotoxin" TEXT,
  "sepA:Shigella extracellular protein A," TEXT,
  "sepA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "sfaD:S fimbrial/F1C minor subunit" TEXT,
  "sfaE:S fimbrial/F1C minor subunit" TEXT,
  "sfaS:S-fimbriae minor subunit" TEXT,
  "sigA:Shigella IgA-like protease homologue" TEXT,
  "sigA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "sitA:Iron transport protein" TEXT,
  "stx1A:Shiga toxin 1, subunit A" TEXT,
  "stx1a-O111-PH:stx1a-O111-PH" TEXT,
  "stx1a-O111-CB168:stx1a-O111-CB168" TEXT,
  "stx1a-O157-AI2001-52:stx1a-O157-AI2001-52" TEXT,
  "stx1a-O157-GPU96MM:stx1a-O157-GPU96MM" TEXT,
  "stx1a-O111-04-06263:stx1a-O111-04-06263" TEXT,
  "stx1a-O111-3385-00:stx1a-O111-3385-00" TEXT,
  "stx1-S.-sonnei-CB7888:stx1-S.-sonnei-CB7888" TEXT,
  "stx1a-O48-94C:stx1a-O48-94C" TEXT,
  "stx1a-O157-FLY16:stx1a-O157-FLY16" TEXT,
  "stx1a-O157-EDL933:stx1a-O157-EDL933" TEXT,
  "stx1a-O165-HI-2:stx1a-O165-HI-2" TEXT,
  "stx1a-ONT-HI-A:stx1a-ONT-HI-A" TEXT,
  "stx1B:Shiga toxin 1, subunit B" TEXT,
  "stx1c-Out-HI-N:stx1c-Out-HI-N" TEXT,
  "stx1c-ONT-HI-B:stx1c-ONT-HI-B" TEXT,
  "stx1c-ONT-HI-C:stx1c-ONT-HI-C" TEXT,
  "stx1c-ONT-BCN26:stx1c-ONT-BCN26" TEXT,
  "stx1c-O174-DG131-3:stx1c-O174-DG131-3" TEXT,
  "stx1d-ONT-92-1251:stx1d-ONT-92-1251" TEXT,
  "stx1d-ONT-92-1252:stx1d-ONT-92-1252" TEXT,
  "stx1d-ONT-AB8SF:stx1d-ONT-AB8SF" TEXT,
  "stx1d-ONT-MHI813:stx1d-ONT-MHI813" TEXT,
  "stx1e-E.-cloacae-M12X01451:stx1e-E.-cloacae-M12X01451" TEXT,
  "stx2A:Shiga toxin 2, subunit A" TEXT,
  "stx2a-A.-haemolyticus:stx2a-A.-haemolyticus" TEXT,
  "stx2a-E.-cloacae-95MV2:stx2a-E.-cloacae-95MV2" TEXT,
  "stx2a-O104-G5506:stx2a-O104-G5506" TEXT,
  "stx2a-O111-928-91:stx2a-O111-928-91" TEXT,
  "stx2a-O113-CL-3:stx2a-O113-CL-3" TEXT,
  "stx2a-O136-VTB60:stx2a-O136-VTB60" TEXT,
  "stx2a-O157-93-111:stx2a-O157-93-111" TEXT,
  "stx2a-O157-A397:stx2a-O157-A397" TEXT,
  "stx2a-O157-EDL933:stx2a-O157-EDL933" TEXT,
  "stx2a-O157-I6581:stx2a-O157-I6581" TEXT,
  "stx2a-O157-SF-258-98:stx2a-O157-SF-258-98" TEXT,
  "stx2a-O178-TS22-08:stx2a-O178-TS22-08" TEXT,
  "stx2a-O22-EBC217:stx2a-O22-EBC217" TEXT,
  "stx2a-O26-126814:stx2a-O26-126814" TEXT,
  "stx2a-O26-FD930:stx2a-O26-FD930" TEXT,
  "stx2a-O48-94C:stx2a-O48-94C" TEXT,
  "stx2a-O8-BMH-17-0027:stx2a-O8-BMH-17-0027" TEXT,
  "stx2a-O8-VTB178:stx2a-O8-VTB178" TEXT,
  "stx2a-O83-N1135:stx2a-O83-N1135" TEXT,
  "stx2a-O88-N2688:stx2a-O88-N2688" TEXT,
  "stx2a-ONT-23765:stx2a-ONT-23765" TEXT,
  "stx2a-ONT-EBC210:stx2a-ONT-EBC210" TEXT,
  "stx2a-ONT-EK9900:stx2a-ONT-EK9900" TEXT,
  "stx2B:Shiga toxin 2, subunit B" TEXT,
  "stx2b-O111-PH:stx2b-O111-PH" TEXT,
  "stx2b-O111-S-1:stx2b-O111-S-1" TEXT,
  "stx2b-O111-S-3:stx2b-O111-S-3" TEXT,
  "stx2b-O118-EH250:stx2b-O118-EH250" TEXT,
  "stx2b-O128-24196-97:stx2b-O128-24196-97" TEXT,
  "stx2b-O146-BMH-17-0036:stx2b-O146-BMH-17-0036" TEXT,
  "stx2b-O174-031:stx2b-O174-031" TEXT,
  "stx2b-O22-3143-97:stx2b-O22-3143-97" TEXT,
  "stx2b-O40-5293-98:stx2b-O40-5293-98" TEXT,
  "stx2b-O8-S-9:stx2b-O8-S-9" TEXT,
  "stx2b-O93-S-5:stx2b-O93-S-5" TEXT,
  "stx2b-O96-S-10:stx2b-O96-S-10" TEXT,
  "stx2b-O96-S-6:stx2b-O96-S-6" TEXT,
  "stx2b-O96-S-7:stx2b-O96-S-7" TEXT,
  "stx2b-ONT-I7606:stx2b-ONT-I7606" TEXT,
  "stx2b-Out-HI-N:stx2b-Out-HI-N" TEXT,
  "stx2b-Out-S-4:stx2b-Out-S-4" TEXT,
  "stx2c-O157-020324:stx2c-O157-020324" TEXT,
  "stx2c-O157-310:stx2c-O157-310" TEXT,
  "stx2c-O157-469:stx2c-O157-469" TEXT,
  "stx2c-O157-A75:stx2c-O157-A75" TEXT,
  "stx2c-O157-C394-03:stx2c-O157-C394-03" TEXT,
  "stx2c-O157-E32511:stx2c-O157-E32511" TEXT,
  "stx2c-O157-FLY16:stx2c-O157-FLY16" TEXT,
  "stx2c-O157-G5101:stx2c-O157-G5101" TEXT,
  "stx2c-O157-V20:stx2c-O157-V20" TEXT,
  "stx2c-O157-Y350-:stx2c-O157-Y350-" TEXT,
  "stx2c-O171-EBC287:stx2c-O171-EBC287" TEXT,
  "stx2c-O171-VTB46:stx2c-O171-VTB46" TEXT,
  "stx2c-O174-031:stx2c-O174-031" TEXT,
  "stx2c-O177-06-5121:stx2c-O177-06-5121" TEXT,
  "stx2c-O177-CB7126:stx2c-O177-CB7126" TEXT,
  "stx2c-ONT-EBC219:stx2c-ONT-EBC219" TEXT,
  "stx2c-ONT-EBC289:stx2c-ONT-EBC289" TEXT,
  "stx2c-OR-TS27-08:stx2c-OR-TS27-08" TEXT,
  "stx2d-C.-freundii-LM76:stx2d-C.-freundii-LM76" TEXT,
  "stx2d-O103-CVM9322:stx2d-O103-CVM9322" TEXT,
  "stx2d-O113-TS03-07:stx2d-O113-TS03-07" TEXT,
  "stx2d-O113-TS21-08:stx2d-O113-TS21-08" TEXT,
  "stx2d-O157-7279:stx2d-O157-7279" TEXT,
  "stx2d-O174-EC1720a:stx2d-O174-EC1720a" TEXT,
  "stx2d-O174-EC173b:stx2d-O174-EC173b" TEXT,
  "stx2d-O2-EC604a:stx2d-O2-EC604a" TEXT,
  "stx2d-O22-KY-O19:stx2d-O22-KY-O19" TEXT,
  "stx2d-O28-MT71:stx2d-O28-MT71" TEXT,
  "stx2d-O55-5905:stx2d-O55-5905" TEXT,
  "stx2d-O6-NV206:stx2d-O6-NV206" TEXT,
  "stx2d-O73-C165-02:stx2d-O73-C165-02" TEXT,
  "stx2d-O8-C466-01B:stx2d-O8-C466-01B" TEXT,
  "stx2d-ONT-EBC275:stx2d-ONT-EBC275" TEXT,
  "stx2d-ONT-EC1871a:stx2d-ONT-EC1871a" TEXT,
  "stx2d-OR-TS06-08:stx2d-OR-TS06-08" TEXT,
  "stx2d1-O91-B2F1:stx2d1-O91-B2F1" TEXT,
  "stx2d2-O91-B2F1:stx2d2-O91-B2F1" TEXT,
  "stx2e-O100-TS01-07:stx2e-O100-TS01-07" TEXT,
  "stx2e-O101-CB10394:stx2e-O101-CB10394" TEXT,
  "stx2e-O101-E-D42:stx2e-O101-E-D42" TEXT,
  "stx2e-O101-E-D43:stx2e-O101-E-D43" TEXT,
  "stx2e-O101-E-D53:stx2e-O101-E-D53" TEXT,
  "stx2e-O101-E-D68:stx2e-O101-E-D68" TEXT,
  "stx2e-O121-NP9621:stx2e-O121-NP9621" TEXT,
  "stx2e-O138-NN:stx2e-O138-NN" TEXT,
  "stx2e-O139-S1191:stx2e-O139-S1191" TEXT,
  "stx2e-O22-3615-99:stx2e-O22-3615-99" TEXT,
  "stx2e-O26-R107:stx2e-O26-R107" TEXT,
  "stx2e-O8-1509W52833:stx2e-O8-1509W52833" TEXT,
  "stx2e-O89-1810F65304:stx2e-O89-1810F65304" TEXT,
  "stx2e-O9-1706T56070:stx2e-O9-1706T56070" TEXT,
  "stx2e-ONT-26725-97:stx2e-ONT-26725-97" TEXT,
  "stx2e-ONT-2771:stx2e-ONT-2771" TEXT,
  "stx2e-ONT-TS03-08:stx2e-ONT-TS03-08" TEXT,
  "stx2e-ONT-TS29-08:stx2e-ONT-TS29-08" TEXT,
  "stx2e-OR-TS09-07:stx2e-OR-TS09-07" TEXT,
  "stx2f-O115-F08-101-31:stx2f-O115-F08-101-31" TEXT,
  "stx2f-O128-T4-97:stx2f-O128-T4-97" TEXT,
  "stx2f-O128-HI8:stx2f-O128-HI8" TEXT,
  "stx2g-O2-7v:stx2g-O2-7v" TEXT,
  "stx2g-O2-HI-11:stx2g-O2-HI-11" TEXT,
  "stx2g-O2-S86:stx2g-O2-S86" TEXT,
  "stx2g-Out-S-8:stx2g-Out-S-8" TEXT,
  "stx2h-O102-STEC299:stx2h-O102-STEC299" TEXT,
  "stx2i-O9-CB10366:stx2i-O9-CB10366" TEXT,
  "stx2j-O101-O101-2012C-4221:stx2j-O101-O101-2012C-4221" TEXT,
  "stx2j-O33-PNUSAE005447:stx2j-O33-PNUSAE005447" TEXT,
  "stx2k-O159-12GZSW01:stx2k-O159-12GZSW01" TEXT,
  "stx2k-O48-STEC309:stx2k-O48-STEC309" TEXT,
  "stx2l-O65-1610T27873:stx2l-O65-1610T27873" TEXT,
  "stx2l-O8-FHI-1106-1092:stx2l-O8-FHI-1106-1092" TEXT,
  "stx2m-O96-2001F31428:stx2m-O96-2001F31428" TEXT,
  "stx2n-O23-2017C-4317:stx2n-O23-2017C-4317" TEXT,
  "stx2o-O85-03-3638:stx2o-O85-03-3638" TEXT,
  "traJ:Protein TraJ (Positive regulator of conjugal transfer operon)" TEXT,
  "subA:Subtilase toxin subunit" TEXT,
  "tccP:Tir-cytoskeleton coupling protein" TEXT,
  "tcpC:Tir domain-containing protein" TEXT,
  "terC:Tellurium ion resistance protein" TEXT,
  "tir:Translocated intimin receptor protein" TEXT,
  "toxB:Toxin B" TEXT,
  "traT:Outer membrane protein complement resistance" TEXT,
  "tsh:Temperature-sensitive hemagglutinin," TEXT,
  "tsh:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "usp:Uropathogenic specific protein" TEXT,
  "vat:Vacuolating autotransporter toxin" TEXT,
  "vat:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "virF:VirF transcriptional activator" TEXT,
  "yehA:Outer membrane lipoprotein, YHD fimbriael cluster" TEXT,
  "yehB:Usher, YHD fimbriael cluster" TEXT,
  "yehC:Chaperone, YHD fimbriael cluster" TEXT,
  "yehD:Major pilin subunit, YHD fimbriael cluster" TEXT,
  "yfcV:Fimbrial protein" TEXT
);

CREATE TABLE typing_report_listeria(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "pathotype" TEXT,
  "pathotype_genes_present" TEXT,
  "serogrouping" TEXT,
  "serotypefinder_software_version" TEXT,
  "serotypefinder_database_version" TEXT,
  "id_threshold_percentage_serotypefinder" TEXT,
  "min_length_threshold_percentage_serotypefinder" TEXT,
  "O_type_serotypefinder" TEXT,
  "H_type_serotypefinder" TEXT,
  "O_type_serotypefinder_long" TEXT,
  "H_type_serotypefinder_long" TEXT,
  "Min_coverage_virulencefinder" TEXT,
  "Min_threshold_identity_virulencefinder" TEXT,
  "ORF2110" TEXT,
  "ORF2819" TEXT,
  "lmo0737" TEXT,
  "lmo1118" TEXT,
  "prs" TEXT
);

CREATE TABLE typing_report_salmonella(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "pathotype" TEXT,
  "pathotype_genes_present" TEXT,
  "Seqsero_Predicted_antigenic_profile" TEXT,
  "Seqsero_Predicted_subspecies" TEXT,
  "Seqsero_Predicted_serotype" TEXT,
  "serotypefinder_software_version" TEXT,
  "serotypefinder_database_version" TEXT,
  "id_threshold_percentage_serotypefinder" TEXT,
  "min_length_threshold_percentage_serotypefinder" TEXT,
  "O_type_serotypefinder" TEXT,
  "H_type_serotypefinder" TEXT,
  "O_type_serotypefinder_long" TEXT,
  "H_type_serotypefinder_long" TEXT,
  "Min_coverage_virulencefinder" TEXT,
  "Min_threshold_identity_virulencefinder" TEXT
);

CREATE TABLE typing_report_yersinia(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
    "MLST_matching_name" TEXT,
  "MLST_ST" TEXT,
  "MLST_alleleIDs" TEXT,
  "MLST_CC" TEXT,
  "pathotype" TEXT,
  "pathotype_genes_present" TEXT,
  "serotypefinder_software_version" TEXT,
  "serotypefinder_database_version" TEXT,
  "id_threshold_percentage_serotypefinder" TEXT,
  "min_length_threshold_percentage_serotypefinder" TEXT,
  "O_type_serotypefinder" TEXT,
  "H_type_serotypefinder" TEXT,
  "O_type_serotypefinder_long" TEXT,
  "H_type_serotypefinder_long" TEXT,
  "Min_coverage_virulencefinder" TEXT,
  "Min_threshold_identity_virulencefinder" TEXT,
  "stx1_subtype_virulencefinder" TEXT,
  "stx2_subtype_virulencefinder" TEXT,
  "eae_virulencefinder" TEXT,
  "aggR_virulencefinder" TEXT,
  "who_risk_level_virulencefinder" TEXT,
  "aafA:AAF/II major fimbrial subunit" TEXT,
  "aafB:AAF/II minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "aafC:Usher, AAF/II assembly unit" TEXT,
  "aafD:Chaperone, AAF/II assembly unit" TEXT,
  "aaiC:Type VI secretion protein" TEXT,
  "aalF:CS23 Minor structural subunit" TEXT,
  "aalG:CS23 Minor structural subunit" TEXT,
  "aap:Dispersin, antiaggregation protein" TEXT,
  "aar:AggR-activated regulator" TEXT,
  "aatA:Dispersin transporter protein" TEXT,
  "afaA:Transcriptional regulator" TEXT,
  "afaB:Periplasmic chaperone" TEXT,
  "afaC:Outer membrane usher protein" TEXT,
  "afaD:Afimbrial adhesion" TEXT,
  "afaE:Adhesin protein" TEXT,
  "afaE8" TEXT,
  "agg3A:AAF/III major fimbrial subunit" TEXT,
  "agg3B:AAF/III minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "agg3C:Usher, AAF/III assembly unit" TEXT,
  "agg3D:Chaperone, AAF/III assembly unit" TEXT,
  "agg4A:AAF/IV major fimbrial subunit" TEXT,
  "agg4B:AAF/IV minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "agg4C:Usher, AAF/IV assembly unit" TEXT,
  "agg4D:Chaperone, AAF/IV assembly unit" TEXT,
  "agg5A" TEXT,
  "aggA:AAF/I major fimbrial subunit" TEXT,
  "aggB:AAF/I minor adhesin. Enterobacteria AfaD invasin protein" TEXT,
  "aggC:Usher, AAF/I assembly unit" TEXT,
  "aggD:Chaperone, AAF/I assembly unit" TEXT,
  "aggR:AraC transcriptional activator" TEXT,
  "air:Enteroaggregative immunoglobulin repeat protein" TEXT,
  "anr:AraC negative regulator" TEXT,
  "astA:Heat-stable enterotoxin 1, astA:EAST-1 heat-stable toxin" TEXT,
  "astA:Heat-stable enterotoxin EAST-1" TEXT,
  "bfpA:Major subunit of bundle-forming pili" TEXT,
  "capU:Hexosyltransferase homolog" TEXT,
  "cba:Colicin B" TEXT,
  "ccI:Cloacin" TEXT,
  "cdtB:Cytolethal distending toxin B" TEXT,
  "cea:Colicin E1" TEXT,
  "celb:Endonuclease colicin E2" TEXT,
  "cfaC" TEXT,
  "chuA:Outer membrane hemin receptor" TEXT,
  "cia:Colicin ia" TEXT,
  "cib:Colicin ib" TEXT,
  "cif:Type III secreted effector" TEXT,
  "clbB:Hybrid non-ribosomal peptide / polyketide megasynthase" TEXT,
  "colE2:Colicin E2" TEXT,
  "colE2-like:Colicin lysis protein precursor E2-like" TEXT,
  "colE8:Colicin E8" TEXT,
  "csgA:curlin major subunit CsgA" TEXT,
  "cma:Colicin M" TEXT,
  "cma:Colicin M activity" TEXT,
  "cnf1:Cytotoxic necrotizing factor" TEXT,
  "cofA:Longus type IV pilus subunit" TEXT,
  "cvaC:Microcin C" TEXT,
  "eae:Intimin" TEXT,
  "eae-b01a-beta:" TEXT,
  "eae-a01-alpha:Intimin-a01-alpha" TEXT,
  "eae-a02-alpha:Intimin-a02-alpha" TEXT,
  "eae-a03-zeta:Intimin-a03-zeta" TEXT,
  "eae-a04-zeta:Intimin-a04-zeta" TEXT,
  "eae-a05a-nu:Intimin-a05a-nu" TEXT,
  "eae-a05b-nu:Intimin-a05b-nu" TEXT,
  "eae-a06-omicron:Intimin-a06-omicron" TEXT,
  "eae-a07-tau:Intimin-a07-tau" TEXT,
  "eae-a08-alpha:Intimin-a08-alpha" TEXT,
  "eae-a09-alpha:Intimin-a09-alpha" TEXT,
  "eae-a10-alpha:Intimin-a10-alpha" TEXT,
  "eae-a11-alpha:Intimin-a11-alpha" TEXT,
  "eae-a12-alpha:Intimin-a12-alpha" TEXT,
  "eae-a13a-alpha:Intimin-a13a-alpha" TEXT,
  "eae-a13b-alpha:Intimin-a13b-alpha" TEXT,
  "eae-a14-alpha:Intimin-a14-alpha" TEXT,
  "eae-a15-alpha:Intimin-a15-alpha" TEXT,
  "eae-a16-alpha:Intimin-a16-alpha" TEXT,
  "eae-a17-alpha:Intimin-a17-alpha" TEXT,
  "eae-a18-alpha:Intimin-a18-alpha" TEXT,
  "eae-b01a-beta:Intimin-b01a-beta" TEXT,
  "eae-b01b-beta:Intimin-b01b-beta" TEXT,
  "eae-b02a-beta:Intimin-b02a-beta" TEXT,
  "eae-b02b-beta:Intimin-b02b-beta" TEXT,
  "eae-b03-beta:Intimin-b03-beta" TEXT,
  "eae-b04-delta:Intimin-b04-delta" TEXT,
  "eae-b05-Citrobacter:Intimin-b05-Citrobacter" TEXT,
  "eae-b06-beta:Intimin-b06-beta" TEXT,
  "eae-b07-beta:Intimin-b07-beta" TEXT,
  "eae-b08-kappa:Intimin-b08-kappa" TEXT,
  "eae-e01-epsilon:Intimin-e01-epsilon" TEXT,
  "eae-e02-epsilon:Intimin-e02-epsilon" TEXT,
  "eae-e03a-epsilon:Intimin-e03a-epsilon" TEXT,
  "eae-e03b-epsilon:Intimin-e03b-epsilon" TEXT,
  "eae-e04-epsilon:Intimin-e04-epsilon" TEXT,
  "eae-e05-eta:Intimin-e05-eta" TEXT,
  "eae-e06-eta:Intimin-e06-eta" TEXT,
  "eae-e07-xi:Intimin-e07-xi" TEXT,
  "eae-e08-pi:Intimin-e08-pi" TEXT,
  "eae-e09-epsilon:Intimin-e09-epsilon" TEXT,
  "eae-e10-epsilon:Intimin-e10-epsilon" TEXT,
  "eae-e11-epsilon:Intimin-e11-epsilon" TEXT,
  "eae-e12-eta:Intimin-e12-eta" TEXT,
  "eae-g01-gamma:Intimin-g01-gamma" TEXT,
  "eae-g02-theta:Intimin-g02-theta" TEXT,
  "eae-g03-mu:Intimin-g03-mu" TEXT,
  "eae-g04-sigma:Intimin-g04-sigma" TEXT,
  "eae-g05-gamma:Intimin-g05-gamma" TEXT,
  "eae-g06-gamma:Intimin-g06-gamma" TEXT,
  "eae-g07-gamma:Intimin-g07-gamma" TEXT,
  "eae-g08-gamma:Intimin-g08-gamma" TEXT,
  "eae-g09-gamma:Intimin-g09-gamma" TEXT,
  "eae-i01-iota:Intimin-i01-iota" TEXT,
  "eae-i02b-iota:Intimin-i02b-iota" TEXT,
  "eae-i03-upsilon:Intimin-i03-upsilon" TEXT,
  "eae-l01-lambda:Intimin-l01-lambda" TEXT,
  "eae-l02-lambda:Intimin-l02-lambda" TEXT,
  "eae-l03-lambda:Intimin-l03-lambda" TEXT,
  "eae-l04a-lambda:Intimin-l04a-lambda" TEXT,
  "eae-l04b-lambda:Intimin-l04b-lambda" TEXT,
  "eae-l05-lambda:Intimin-l05-lambda" TEXT,
  "eae-r01-rho:Intimin-r01-rho" TEXT,
  "eae-r02-rho:Intimin-r02-rho" TEXT,
  "eae-r03-rho:Intimin-r03-rho" TEXT,
  "eae-r04-rho:Intimin-r04-rho" TEXT,
  "eatA:enterotoxigenic E. coli (ETEC) autotransporter A" TEXT,
  "eatA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "efa1:EHEC factor for adherence; lymphostatin Efa1-LifA" TEXT,
  "ehxA:Enterohaemolysin" TEXT,
  "eilA:Salmonella HilA homolog" TEXT,
  "eltIAB-1:Heat-labile enterotoxin LTIh-1" TEXT,
  "eltIAB-2:Heat-labile enterotoxin LTIh-2" TEXT,
  "eltIAB-3:Heat-labile enterotoxin LTIh-3" TEXT,
  "eltIAB-4:Heat-labile enterotoxin LTIh-4" TEXT,
  "eltIAB-5:Heat-labile enterotoxin LTIh-5" TEXT,
  "eltIAB-6:Heat-labile enterotoxin LTIh-6" TEXT,
  "eltIAB-7:Heat-labile enterotoxin LTIh-7" TEXT,
  "eltIAB-8:Heat-labile enterotoxin LTIh-8" TEXT,
  "eltIAB-9:Heat-labile enterotoxin LTIh9" TEXT,
  "eltIAB-10:Heat-labile enterotoxin LTIh-10" TEXT,
  "eltIAB-11:Heat-labile enterotoxin LTIh-11" TEXT,
  "eltIAB-12:Heat-labile enterotoxin LTIh-12" TEXT,
  "eltIAB-13:Heat-labile enterotoxin LTIh-13" TEXT,
  "eltIAB-14:Heat-labile enterotoxin LTIh-14" TEXT,
  "eltIAB-15:Heat-labile enterotoxin LTIh-15" TEXT,
  "eltIAB-15b:Heat-labile enterotoxin LTIh-15b" TEXT,
  "eltIAB-16:Heat-labile enterotoxin LTIh-16" TEXT,
  "eltIAB-17:Heat-labile enterotoxin LTIh-17" TEXT,
  "eltIAB-18:Heat-labile enterotoxin LTIh-18" TEXT,
  "eltIAB-19:Heat-labile enterotoxin LTIh-19" TEXT,
  "eltIAB-20:Heat-labile enterotoxin LTIh-20" TEXT,
  "eltIAB-21:Heat-labile enterotoxin LTIh-21" TEXT,
  "eltIAB-22:Heat-labile enterotoxin LTIh-22" TEXT,
  "eltIAB-23:Heat-labile enterotoxin LTIh-23" TEXT,
  "eltIAB-24:Heat-labile enterotoxin LTIh-24" TEXT,
  "eltIAB-25:Heat-labile enterotoxin LTIh-25" TEXT,
  "eltIAB-26:Heat-labile enterotoxin LTIh-26" TEXT,
  "eltIAB-27:Heat-labile enterotoxin LTIh-27" TEXT,
  "eltIAB-28:Heat-labile enterotoxin LTIh-28" TEXT,
  "eltIAB-29:Heat-labile enterotoxin LTIh-29" TEXT,
  "eltIAB-30:Heat-labile enterotoxin LTIh-30" TEXT,
  "eltIAB-31:Heat-labile enterotoxin LTIh-31" TEXT,
  "eltIAB-33:Heat-labile enterotoxin LTIh-32" TEXT,
  "eltIAB-33:Heat-labile enterotoxin LTIh-33" TEXT,
  "eltIIAB-a:Heat-labile enterotoxin LTII-a" TEXT,
  "eltIIAB-b1:Heat-labile enterotoxin LTII-b1" TEXT,
  "eltIIAB-b2:Heat-labile enterotoxin LTII-b2" TEXT,
  "eltIIAB-c1:Heat-labile enterotoxin LTII-c1" TEXT,
  "eltIIAB-c2:Heat-labile enterotoxin LTII-c2" TEXT,
  "eltIIAB-c3:Heat-labile enterotoxin LTII-c3" TEXT,
  "eltIIAB-c4:Heat-labile enterotoxin LTII-c4" TEXT,
  "eltIIAB-c5:Heat-labile enterotoxin LTII-c5" TEXT,
  "eltIIAB-c6:Heat-labile enterotoxin LTII-c6" TEXT,
  "eltIIAB-c7:Heat-labile enterotoxin LTII-c7" TEXT,
  "eltIIAB-c8:Heat-labile enterotoxin LTII-c8" TEXT,
  "eltIIAB-c9:Heat-labile enterotoxin LTII-c9" TEXT,
  "eltIIAB-d1:Heat-labile enterotoxin LTII-d1" TEXT,
  "eltIIAB-d2:Heat-labile enterotoxin LTII-d2" TEXT,
  "eltIIAB-e:Heat-labile enterotoxin LTII-e" TEXT,
  "epeA:enterohemorrhagic E. coli EHEC plasmid-encoded autotransporter" TEXT,
  "epeA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espA:Type III secretions system" TEXT,
  "espB:Secreted protein B" TEXT,
  "espC:EPEC secreted protein C" TEXT,
  "espC:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espF:EPEC secreted protein F; Type III secretion system" TEXT,
  "espI:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "espJ:Prophage-encoded type III secretion system effector" TEXT,
  "espP:Extracellular serine protease plasmid-encoded" TEXT,
  "espP:Putative exoprotein precursor" TEXT,
  "espP:Serine protease autotransporter EspP" TEXT,
  "estap-STa1:Heat-stable enterotoxin STa1 porcine variant" TEXT,
  "estah-STa2:Heat-stable enterotoxin STa2 human variant" TEXT,
  "estah-STa3:Heat-stable enterotoxin STa3 human variant" TEXT,
  "estap-STa4:Heat-stable enterotoxin STa4 porcine variant" TEXT,
  "estap-STa5:Heat-stable enterotoxin STa5 porcine variant" TEXT,
  "estap-STa6:Heat-stable enterotoxin STa6 porcine variant" TEXT,
  "estap-STa7:Heat-stable enterotoxin STa7 porcine variant" TEXT,
  "estap-STa8:Heat-stable enterotoxin STa8 porcine variant" TEXT,
  "estap-STa9:Heat-stable enterotoxin STa9 porcine variant" TEXT,
  "estb-STb1:Heat-stable enterotoxin STb1 porcine variant" TEXT,
  "estb-STb2:Heat-stable enterotoxin STb2 human variant" TEXT,
  "etpD:Type II secretion protein" TEXT,
  "etsC:Putative type I secretion outer membrane protein" TEXT,
  "f17A" TEXT,
  "f17G" TEXT,
  "faeC:F4 (K88) Minor fimbrial subunits" TEXT,
  "faeD:F4 (K88) Usher" TEXT,
  "faeF:F4 (K88) Minor fimbrial subunit" TEXT,
  "faeJ:F4 (K88) Fimbria minor subunit" TEXT,
  "fanA:Involved in biogenesis of K99/F5 fimbriae" TEXT,
  "fasA:Fimbriae 987P/F6 subunit" TEXT,
  "fdeC:intimin-like adhesin FdeC" TEXT,
  "fedA:Fimbrial protein F107 subunit A" TEXT,
  "fedF:Fimbrial adhesin AC precursor" TEXT,
  "fimH:Type 1 fimbriae" TEXT,
  "fim41a:Mature Fim41a/F41 protein" TEXT,
  "focC:S fimbrial/F1C minor subunit" TEXT,
  "focCsfaE" TEXT,
  "focG:F1C adhesion" TEXT,
  "focI:S fimbrial/F1C minor subunit" TEXT,
  "fyuA:Siderophore receptor" TEXT,
  "gad:Glutamate decarboxylase" TEXT,
  "hha:hemolysin expression modulator Hha (previous rmoA)" TEXT,
  "hlyE:Avian E. coli haemolysin" TEXT,
  "hlyF:Hemolysin F" TEXT,
  "hra:Heat-resistant agglutinin" TEXT,
  "ibeA:Invasin of brain endothelial cells" TEXT,
  "iha:Adherence protein" TEXT,
  "ipaD:Invasion protein Shigella flexneri" TEXT,
  "ipaH9.8:Invasion plasmid antigen" TEXT,
  "ireA:Siderophore receptor" TEXT,
  "iroN:Enterobactin siderophore receptor protein" TEXT,
  "irp2:High molecular weight protein 2 non-ribosomal peptide synthetase" TEXT,
  "iss:Increased serum survival" TEXT,
  "iucC:Aerobactin synthetase" TEXT,
  "iutA:Ferric aerobactin receptor" TEXT,
  "K88ab:K88/F4 protein subunit" TEXT,
  "katP:Plasmid-encoded catalase peroxidase" TEXT,
  "kpsE:Capsule polysaccharide export inner-membrane protein" TEXT,
  "kpsM:Polysialic acid transport protein" TEXT,
  "kpsM_K11:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsM_K15:Polysialic acid transport protein; Group 3 capsule" TEXT,
  "kpsM_K19:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsM_K19K23:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMII:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K1:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K23:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K24:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K4:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K5:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K52:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMII_K94:Polysialic acid transport protein; Group 2 capsule" TEXT,
  "kpsMIII:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K10:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K96:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "kpsMIII_K98:ABC-type polysaccharide/polyol phosphate export systems permease; Group 3 capsule" TEXT,
  "lngA:Longus type IV pilus" TEXT,
  "lpfA:Long polar fimbriae" TEXT,
  "ltcA:Heat-labile enterotoxin A subunit" TEXT,
  "mcbA:Bacteriocin microcin B17" TEXT,
  "mchB:Microcin H47 part of colicin H" TEXT,
  "mchC:MchC protein" TEXT,
  "mchF:ABC transporter protein MchF" TEXT,
  "mcmA:Microcin M part of colicin H" TEXT,
  "neuC:Polysialic acid capsule biosynthesis protein" TEXT,
  "nfaE:Diffuse adherence fibrillar adhesin gene" TEXT,
  "nleA:Non-LEE encoded effector A" TEXT,
  "nleB:Non-LEE encoded effector B" TEXT,
  "nleC:Non-LEE encoded effector C" TEXT,
  "nlpI:lipoprotein NlpI precursor" TEXT,
  "ompT:Outer membrane protease (protein protease 7)" TEXT,
  "ORF3:Isoprenoid Biosynthesis" TEXT,
  "ORF4:Putative isopentenyl-diphosphate delta-isomerase" TEXT,
  "papA_F11:Major pilin subunit F11" TEXT,
  "papA_F12:Major pilin subunit F12" TEXT,
  "papA_F13:Major pilin subunit F13" TEXT,
  "papA_F14:Major pilin subunit F14" TEXT,
  "papA_F1651A:Major pilin subunit F1651A" TEXT,
  "papA_F19:Major pilin subunit F19" TEXT,
  "papA_F20:Major pilin subunit F20" TEXT,
  "papA_F40:Major pilin subunit F40" TEXT,
  "papA_F43:Major pilin subunit F43" TEXT,
  "papA_F48:Major pilin subunit F48" TEXT,
  "papA_F536:Major pilin subunit F536" TEXT,
  "papA_F7-1:Major pilin subunit F7-1" TEXT,
  "papA_F7-2:Major pilin subunit F7-2" TEXT,
  "papA_F8:Major pilin subunit F8" TEXT,
  "papA_F9:Major pilin subunit F9" TEXT,
  "papA_feiA_F8:Major pilin subunit F8" TEXT,
  "papA_ffiA_F15:Major pilin subunit F15" TEXT,
  "papA_ffoA_F14:Major pilin subunit F14" TEXT,
  "papA_fsiA_F16:Major pilin subunit F16" TEXT,
  "papA_fteA_F10:Major pilin subunit F10" TEXT,
  "papA_prsA_F12:Major pilin subunit F12" TEXT,
  "papC:Outer membrane usher P fimbriae" TEXT,
  "perA:EPEC adherence factor" TEXT,
  "pet:Plasmid-encoded toxin, pet:Autotransporter enterotoxin" TEXT,
  "pic:Protease involved in intestinal colonization" TEXT,
  "pic:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "rpeA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "saa:Auto agglutinating adhesin" TEXT,
  "sat:Secreted autotransporter toxin" TEXT,
  "sat:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "senB:Plasmid-encoded enterotoxin" TEXT,
  "sepA:Shigella extracellular protein A," TEXT,
  "sepA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "sfaD:S fimbrial/F1C minor subunit" TEXT,
  "sfaE:S fimbrial/F1C minor subunit" TEXT,
  "sfaS:S-fimbriae minor subunit" TEXT,
  "sigA:Shigella IgA-like protease homologue" TEXT,
  "sigA:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "sitA:Iron transport protein" TEXT,
  "stx1A:Shiga toxin 1, subunit A" TEXT,
  "stx1a-O111-PH:stx1a-O111-PH" TEXT,
  "stx1a-O111-CB168:stx1a-O111-CB168" TEXT,
  "stx1a-O157-AI2001-52:stx1a-O157-AI2001-52" TEXT,
  "stx1a-O157-GPU96MM:stx1a-O157-GPU96MM" TEXT,
  "stx1a-O111-04-06263:stx1a-O111-04-06263" TEXT,
  "stx1a-O111-3385-00:stx1a-O111-3385-00" TEXT,
  "stx1-S.-sonnei-CB7888:stx1-S.-sonnei-CB7888" TEXT,
  "stx1a-O48-94C:stx1a-O48-94C" TEXT,
  "stx1a-O157-FLY16:stx1a-O157-FLY16" TEXT,
  "stx1a-O157-EDL933:stx1a-O157-EDL933" TEXT,
  "stx1a-O165-HI-2:stx1a-O165-HI-2" TEXT,
  "stx1a-ONT-HI-A:stx1a-ONT-HI-A" TEXT,
  "stx1B:Shiga toxin 1, subunit B" TEXT,
  "stx1c-Out-HI-N:stx1c-Out-HI-N" TEXT,
  "stx1c-ONT-HI-B:stx1c-ONT-HI-B" TEXT,
  "stx1c-ONT-HI-C:stx1c-ONT-HI-C" TEXT,
  "stx1c-ONT-BCN26:stx1c-ONT-BCN26" TEXT,
  "stx1c-O174-DG131-3:stx1c-O174-DG131-3" TEXT,
  "stx1d-ONT-92-1251:stx1d-ONT-92-1251" TEXT,
  "stx1d-ONT-92-1252:stx1d-ONT-92-1252" TEXT,
  "stx1d-ONT-AB8SF:stx1d-ONT-AB8SF" TEXT,
  "stx1d-ONT-MHI813:stx1d-ONT-MHI813" TEXT,
  "stx1e-E.-cloacae-M12X01451:stx1e-E.-cloacae-M12X01451" TEXT,
  "stx2A:Shiga toxin 2, subunit A" TEXT,
  "stx2a-A.-haemolyticus:stx2a-A.-haemolyticus" TEXT,
  "stx2a-E.-cloacae-95MV2:stx2a-E.-cloacae-95MV2" TEXT,
  "stx2a-O104-G5506:stx2a-O104-G5506" TEXT,
  "stx2a-O111-928-91:stx2a-O111-928-91" TEXT,
  "stx2a-O113-CL-3:stx2a-O113-CL-3" TEXT,
  "stx2a-O136-VTB60:stx2a-O136-VTB60" TEXT,
  "stx2a-O157-93-111:stx2a-O157-93-111" TEXT,
  "stx2a-O157-A397:stx2a-O157-A397" TEXT,
  "stx2a-O157-EDL933:stx2a-O157-EDL933" TEXT,
  "stx2a-O157-I6581:stx2a-O157-I6581" TEXT,
  "stx2a-O157-SF-258-98:stx2a-O157-SF-258-98" TEXT,
  "stx2a-O178-TS22-08:stx2a-O178-TS22-08" TEXT,
  "stx2a-O22-EBC217:stx2a-O22-EBC217" TEXT,
  "stx2a-O26-126814:stx2a-O26-126814" TEXT,
  "stx2a-O26-FD930:stx2a-O26-FD930" TEXT,
  "stx2a-O48-94C:stx2a-O48-94C" TEXT,
  "stx2a-O8-BMH-17-0027:stx2a-O8-BMH-17-0027" TEXT,
  "stx2a-O8-VTB178:stx2a-O8-VTB178" TEXT,
  "stx2a-O83-N1135:stx2a-O83-N1135" TEXT,
  "stx2a-O88-N2688:stx2a-O88-N2688" TEXT,
  "stx2a-ONT-23765:stx2a-ONT-23765" TEXT,
  "stx2a-ONT-EBC210:stx2a-ONT-EBC210" TEXT,
  "stx2a-ONT-EK9900:stx2a-ONT-EK9900" TEXT,
  "stx2B:Shiga toxin 2, subunit B" TEXT,
  "stx2b-O111-PH:stx2b-O111-PH" TEXT,
  "stx2b-O111-S-1:stx2b-O111-S-1" TEXT,
  "stx2b-O111-S-3:stx2b-O111-S-3" TEXT,
  "stx2b-O118-EH250:stx2b-O118-EH250" TEXT,
  "stx2b-O128-24196-97:stx2b-O128-24196-97" TEXT,
  "stx2b-O146-BMH-17-0036:stx2b-O146-BMH-17-0036" TEXT,
  "stx2b-O174-031:stx2b-O174-031" TEXT,
  "stx2b-O22-3143-97:stx2b-O22-3143-97" TEXT,
  "stx2b-O40-5293-98:stx2b-O40-5293-98" TEXT,
  "stx2b-O8-S-9:stx2b-O8-S-9" TEXT,
  "stx2b-O93-S-5:stx2b-O93-S-5" TEXT,
  "stx2b-O96-S-10:stx2b-O96-S-10" TEXT,
  "stx2b-O96-S-6:stx2b-O96-S-6" TEXT,
  "stx2b-O96-S-7:stx2b-O96-S-7" TEXT,
  "stx2b-ONT-I7606:stx2b-ONT-I7606" TEXT,
  "stx2b-Out-HI-N:stx2b-Out-HI-N" TEXT,
  "stx2b-Out-S-4:stx2b-Out-S-4" TEXT,
  "stx2c-O157-020324:stx2c-O157-020324" TEXT,
  "stx2c-O157-310:stx2c-O157-310" TEXT,
  "stx2c-O157-469:stx2c-O157-469" TEXT,
  "stx2c-O157-A75:stx2c-O157-A75" TEXT,
  "stx2c-O157-C394-03:stx2c-O157-C394-03" TEXT,
  "stx2c-O157-E32511:stx2c-O157-E32511" TEXT,
  "stx2c-O157-FLY16:stx2c-O157-FLY16" TEXT,
  "stx2c-O157-G5101:stx2c-O157-G5101" TEXT,
  "stx2c-O157-V20:stx2c-O157-V20" TEXT,
  "stx2c-O157-Y350-:stx2c-O157-Y350-" TEXT,
  "stx2c-O171-EBC287:stx2c-O171-EBC287" TEXT,
  "stx2c-O171-VTB46:stx2c-O171-VTB46" TEXT,
  "stx2c-O174-031:stx2c-O174-031" TEXT,
  "stx2c-O177-06-5121:stx2c-O177-06-5121" TEXT,
  "stx2c-O177-CB7126:stx2c-O177-CB7126" TEXT,
  "stx2c-ONT-EBC219:stx2c-ONT-EBC219" TEXT,
  "stx2c-ONT-EBC289:stx2c-ONT-EBC289" TEXT,
  "stx2c-OR-TS27-08:stx2c-OR-TS27-08" TEXT,
  "stx2d-C.-freundii-LM76:stx2d-C.-freundii-LM76" TEXT,
  "stx2d-O103-CVM9322:stx2d-O103-CVM9322" TEXT,
  "stx2d-O113-TS03-07:stx2d-O113-TS03-07" TEXT,
  "stx2d-O113-TS21-08:stx2d-O113-TS21-08" TEXT,
  "stx2d-O157-7279:stx2d-O157-7279" TEXT,
  "stx2d-O174-EC1720a:stx2d-O174-EC1720a" TEXT,
  "stx2d-O174-EC173b:stx2d-O174-EC173b" TEXT,
  "stx2d-O2-EC604a:stx2d-O2-EC604a" TEXT,
  "stx2d-O22-KY-O19:stx2d-O22-KY-O19" TEXT,
  "stx2d-O28-MT71:stx2d-O28-MT71" TEXT,
  "stx2d-O55-5905:stx2d-O55-5905" TEXT,
  "stx2d-O6-NV206:stx2d-O6-NV206" TEXT,
  "stx2d-O73-C165-02:stx2d-O73-C165-02" TEXT,
  "stx2d-O8-C466-01B:stx2d-O8-C466-01B" TEXT,
  "stx2d-ONT-EBC275:stx2d-ONT-EBC275" TEXT,
  "stx2d-ONT-EC1871a:stx2d-ONT-EC1871a" TEXT,
  "stx2d-OR-TS06-08:stx2d-OR-TS06-08" TEXT,
  "stx2d1-O91-B2F1:stx2d1-O91-B2F1" TEXT,
  "stx2d2-O91-B2F1:stx2d2-O91-B2F1" TEXT,
  "stx2e-O100-TS01-07:stx2e-O100-TS01-07" TEXT,
  "stx2e-O101-CB10394:stx2e-O101-CB10394" TEXT,
  "stx2e-O101-E-D42:stx2e-O101-E-D42" TEXT,
  "stx2e-O101-E-D43:stx2e-O101-E-D43" TEXT,
  "stx2e-O101-E-D53:stx2e-O101-E-D53" TEXT,
  "stx2e-O101-E-D68:stx2e-O101-E-D68" TEXT,
  "stx2e-O121-NP9621:stx2e-O121-NP9621" TEXT,
  "stx2e-O138-NN:stx2e-O138-NN" TEXT,
  "stx2e-O139-S1191:stx2e-O139-S1191" TEXT,
  "stx2e-O22-3615-99:stx2e-O22-3615-99" TEXT,
  "stx2e-O26-R107:stx2e-O26-R107" TEXT,
  "stx2e-O8-1509W52833:stx2e-O8-1509W52833" TEXT,
  "stx2e-O89-1810F65304:stx2e-O89-1810F65304" TEXT,
  "stx2e-O9-1706T56070:stx2e-O9-1706T56070" TEXT,
  "stx2e-ONT-26725-97:stx2e-ONT-26725-97" TEXT,
  "stx2e-ONT-2771:stx2e-ONT-2771" TEXT,
  "stx2e-ONT-TS03-08:stx2e-ONT-TS03-08" TEXT,
  "stx2e-ONT-TS29-08:stx2e-ONT-TS29-08" TEXT,
  "stx2e-OR-TS09-07:stx2e-OR-TS09-07" TEXT,
  "stx2f-O115-F08-101-31:stx2f-O115-F08-101-31" TEXT,
  "stx2f-O128-T4-97:stx2f-O128-T4-97" TEXT,
  "stx2f-O128-HI8:stx2f-O128-HI8" TEXT,
  "stx2g-O2-7v:stx2g-O2-7v" TEXT,
  "stx2g-O2-HI-11:stx2g-O2-HI-11" TEXT,
  "stx2g-O2-S86:stx2g-O2-S86" TEXT,
  "stx2g-Out-S-8:stx2g-Out-S-8" TEXT,
  "stx2h-O102-STEC299:stx2h-O102-STEC299" TEXT,
  "stx2i-O9-CB10366:stx2i-O9-CB10366" TEXT,
  "stx2j-O101-O101-2012C-4221:stx2j-O101-O101-2012C-4221" TEXT,
  "stx2j-O33-PNUSAE005447:stx2j-O33-PNUSAE005447" TEXT,
  "stx2k-O159-12GZSW01:stx2k-O159-12GZSW01" TEXT,
  "stx2k-O48-STEC309:stx2k-O48-STEC309" TEXT,
  "stx2l-O65-1610T27873:stx2l-O65-1610T27873" TEXT,
  "stx2l-O8-FHI-1106-1092:stx2l-O8-FHI-1106-1092" TEXT,
  "stx2m-O96-2001F31428:stx2m-O96-2001F31428" TEXT,
  "stx2n-O23-2017C-4317:stx2n-O23-2017C-4317" TEXT,
  "stx2o-O85-03-3638:stx2o-O85-03-3638" TEXT,
  "traJ:Protein TraJ (Positive regulator of conjugal transfer operon)" TEXT,
  "subA:Subtilase toxin subunit" TEXT,
  "tccP:Tir-cytoskeleton coupling protein" TEXT,
  "tcpC:Tir domain-containing protein" TEXT,
  "terC:Tellurium ion resistance protein" TEXT,
  "tir:Translocated intimin receptor protein" TEXT,
  "toxB:Toxin B" TEXT,
  "traT:Outer membrane protein complement resistance" TEXT,
  "tsh:Temperature-sensitive hemagglutinin," TEXT,
  "tsh:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "usp:Uropathogenic specific protein" TEXT,
  "vat:Vacuolating autotransporter toxin" TEXT,
  "vat:serine protease autotransporters of Enterobacteriaceae (SPATE)" TEXT,
  "virF:VirF transcriptional activator" TEXT,
  "yehA:Outer membrane lipoprotein, YHD fimbriael cluster" TEXT,
  "yehB:Usher, YHD fimbriael cluster" TEXT,
  "yehC:Chaperone, YHD fimbriael cluster" TEXT,
  "yehD:Major pilin subunit, YHD fimbriael cluster" TEXT,
  "yfcV:Fimbrial protein" TEXT
);